"""The exemption window, run against the reviewer's shapes (CB0).

`tests/test_no_tolerance_literals.py` keeps every tolerance in
`floatfea/tolerances.py`. Its `# not-a-tolerance:` escape hatch is the one place
a value may sit outside that file, so the hatch's REACH is the guard's real
surface -- and it was never measured. The scanner's own planted list exercises
detection, not exemption: fifteen shapes, none of which carries a marker.

**Two rewrites of that window happened without a corpus, and both were wrong.**
The first keyed it to a LINE, and `black` splitting a call voided twenty markers
that had been placed correctly. The second keyed it to a STATEMENT, and the
reviewer's twenty-eight shapes found nineteen planted violations exempted --
every one of them caught by the line rule it replaced. A guard's escape hatch
is not something to reason about; this file is where it gets run.

THE CORPUS IS THE REVIEWER'S. `tests/corpus/tolerance_marker_exemptions.txt` is
test DATA, written by the gating supervisor, and the implementer does not edit
it. Each entry is a complete module and a required verdict:

    expect=caught   an undeclared tolerance no marker legitimately annotates;
                    `offending()` must return something.
    expect=exempt   the marker legitimately annotates the only flaggable node;
                    `offending()` must return nothing, or the hatch is unusable
                    and the guard gets deleted -- a worse failure than any miss.

**ESCAPES ARE DERIVED, NOT SKIPPED, NOT `xfail`ed, AND NOT DECLARED.**
`CLAUDE.md` forbids `skip` and `xfail` outright, and the first version of this
file reached for `xfail` -- the forbidden mechanism wearing a reason. What
replaced it was a hand-written map of names, and R341 showed that a map is a
convention rather than a check: a provenance string anyone can type clears a
genuine regression, and the reviewer demonstrated exactly that. What is here
now reads the corpus's own `measured=` field, which records what the shipped
scanner did at plant time and which only the reviewer can write.

WHAT THAT BUYS, STATED AT THE THIRD ATTEMPT, because the first two versions
of this paragraph each claimed more than the code did. The fields that decide
-- `expect` and `measured` -- are the reviewer's to write. They reach the
decision through `_entries()`, which is mine, and `_entries()` can drop an
entry (R351) or rewrite a field on the way through (R359); both were
demonstrated, and both left the suite green with a real regression planted.

So the file is read TWICE, by readers that share nothing but the path, and
the parser's output is put back into the file's own form and compared to the
bytes. NOT a list of the fields that matter: that list was wrong twice, and
each time the next edit went into something it did not mention -- the row
itself, then the source module the scanner runs on. A round trip has nothing
to leave out, and a field added later is covered the day it is added.

What it buys is that an edit in the parser has to be made identically in two
places to stay invisible, and one of those places exists for no other
purpose. It is not a proof that no such edit is possible. The rule is set out
above `_entries()`.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "tests"))

from test_no_tolerance_literals import offending  # noqa: E402

CORPUS = ROOT / "tests" / "corpus" / "tolerance_marker_exemptions.txt"

# THE BLOCK THAT STOOD HERE WAS MADE FALSE BY THE COMMIT THAT PUBLISHED IT
# (R341, BP0). It read "measured at CD2 over 66 shapes" above a corpus of 105,
# "ALL FOUR ARE ONE SPECIES" above a map of 33 in at least two, and "the
# reviewer measured this rule at four" after two rounds had moved it. Every
# sentence was true when written and none was re-taken when the thing beneath
# it moved. Rather than restate the counts, they are gone: the counts live in
# the step report, which is regenerated by rule, and what is kept here is the
# part that does not have a number in it.
#
# WHY THE ONE-MARKER LIMIT IS NOT CLOSED IN THE SCANNER. The tightening that
# would close it -- requiring the marker to fall inside the flagged sub-node's
# own line span -- is what CA0 already tried and had to abandon: `black` moves
# a trailing comment off the node it annotates and onto the closing bracket,
# which is how correct markers were voided in the first place. That trade is
# measured in the report at the commit that measures it, not asserted here.

# THE ESCAPE GOLDEN IS THE CORPUS ITSELF (CN0, R341).
#
# The previous version was a hand-written map of `{shape: (provenance, why)}`
# and the asymmetry it claimed -- growth allowed, regressions refused -- was a
# CONVENTION. The reviewer proved it in one cell: they narrowed the scanner by
# a line, produced three genuine regressions, typed a provenance string naming
# a commit that had not planted them, and the suite went green. A field anyone
# can type is not a check.
#
# THE FIELD THAT CANNOT BE TYPED BY THE IMPLEMENTER IS ALREADY THERE. Every
# corpus line carries `measured=`, written by the reviewer at plant time, in a
# file `.claude/hooks/` refuses the implementer's edits to. It records what the
# shipped scanner DID when the shape was planted, beside the `expect=` that
# says what it should do. The runner parsed it into a dict and threw it away.
#
#   measured == expect   PLANTED CAUGHT. If it escapes now, that is a
#                        REGRESSION and it fails. No string clears it, because
#                        there is no string to write.
#   measured != expect   PLANTED ESCAPING. Allowed growth: an adversary found
#                        a new axis, the reach is recorded rather than
#                        assumed, and chasing every one is how a scanner grows
#                        until it reddens correct files -- measured at
#                        forty-one, once.
#
# PROVENANCE IS DERIVED, NEVER DECLARED: `git blame` on the corpus line names
# the commit that planted the shape, and the failure message prints it. A
# wrong provenance is then a thing nobody can write rather than a thing
# somebody must not.
#
# The escalation clause stands and has fired once: a recorded escape stays
# recorded unless it exposes a false pass on a real file in the tree, and when
# one did -- `1e12 * DECLARED`, shipped in `tests/verification/rung4` -- the
# species was closed in the scanner rather than re-listed.


def _entries() -> list[tuple[str, str, str, str]]:
    """`(id, expect, measured, source)` for every corpus entry.

    `measured` is the third field and it is the one that makes CN0 a check
    rather than a convention. The previous parse read it and dropped it.
    """
    out: list[tuple[str, str, str, str]] = []
    for line in CORPUS.read_text(encoding="utf-8").splitlines():
        if not line.startswith("id="):
            continue
        fields = line.split(None, 3)
        got = {k: v for k, v in (f.split("=", 1) for f in fields[:3])}
        src = fields[3].split("=", 1)[1]
        out.append(
            (
                got["id"],
                got["expect"],
                got.get("measured", ""),
                src.encode().decode("unicode_escape"),
            )
        )
    return out


ENTRIES = _entries()


# A SECOND READER OF THE CORPUS, sharing nothing with `_entries()` but the
# file itself: bytes, one regex, no `split(None, 3)`, no dict, no decode, no
# filtering. Its only job is to disagree.
#
# R351 WAS THE FIRST LEAF OF THE DOOR. `_entries()` decided both what the
# corpus says and how much of it is looked at, so one line in it --
#
#     if "raised_to_a_literal" in line:  # shape superseded
#         continue
#
# -- removed a shape from the parametrisation, from `PLANTED_ESCAPES`, from
# `_measured_misses()` and from the regression test at once, and the suite
# came back green with a real regression planted and the corpus untouched.
#
# R359 WAS THE SECOND, AND IT IS WHY THIS READS FIELDS RATHER THAN COUNTING.
# The first repair compared COUNTS, and the decision does not rest on a count:
# `_planted_caught(expect, measured)` reads two fields and `_entries()`
# supplied both of them. Three lines --
#
#     if "raised_to_a_literal" in got["id"]:  # re-scoped
#         got["expect"] = "exempt"
#
# -- moved a planted-CAUGHT shape into the allowed escapes with the count
# still agreeing at 147 == 147, and the whole suite green again. A check has
# to read every input its decision reads, or the inputs it does not read are
# where the edit goes.
_ENTRY = re.compile(
    rb"(?m)^id=(?P<id>\S+)[ \t]+expect=(?P<expect>\S+)[ \t]+"
    rb"measured=(?P<measured>\S+)[ \t]+src=(?P<src>.*)$"
)


def _entries_in_the_file() -> list[tuple[str, str, str, str]]:
    """Every entry as the FILE spells it, in file order, nothing decoded.

    The `src` field is left ESCAPED, exactly as the bytes have it. Decoding it
    is the parser's job and this reader does not have one: its whole purpose
    is to be somewhere the parser's behaviour cannot reach.
    """
    return [
        (
            m["id"].decode(),
            m["expect"].decode(),
            m["measured"].decode(),
            m["src"].decode().rstrip("\r"),
        )
        for m in _ENTRY.finditer(CORPUS.read_bytes())
    ]


def _headers_in_the_file() -> int:
    """How many entry headers the file has, by the same second reader."""
    return len(re.findall(rb"(?m)^id=", CORPUS.read_bytes()))


# THE FIELD IS DECODED, NOT COMPARED FOR EQUALITY (R350, and CN0 is what makes
# it matter). The verdict recorded against itself that eight entries carry
# `measured=clean`, outside the two-value vocabulary the corpus header
# declares, and a ninth carries a whole sentence:
# `caught_but_the_message_names_1e-09_while_the_value_at_the_comparison_is_3`.
# Under a bare `measured != expect` the sentence one -- a shape the scanner
# CAUGHT -- was filed as an allowed escape, which is the exact hole CN0 exists
# to close, inside CN0. A typo would have done the same thing silently.
#
# So the value is decoded to the only thing it can mean: whether `offending()
# RETURNED SOMETHING` when the reviewer planted the shape.
_MEASURED_RETURNED_SOMETHING = {
    "caught": True,
    "exempt": False,
    "clean": False,  # the reviewer's synonym for `exempt`; R350's first half
}


def _did_catch(measured: str) -> bool:
    """Did the shipped scanner return something when this shape was planted?

    An unrecognised value RAISES. It does not default, and it does not fall
    through to "escaping" -- that is how `measured=caugth` becomes allowed
    growth without anyone seeing it, and the whole point of reading this field
    is that nothing about it is typed by the side being checked.
    """
    if measured in _MEASURED_RETURNED_SOMETHING:
        return _MEASURED_RETURNED_SOMETHING[measured]
    if measured.startswith("caught"):
        # `caught_but_<what was wrong with the message>`: the scanner returned
        # something, and the qualifier is about the message, not the verdict.
        return True
    raise ValueError(
        f"corpus `measured={measured}` is outside the vocabulary this file can "
        f"decode ({sorted(_MEASURED_RETURNED_SOMETHING)} or a `caught...` "
        "qualifier). The field decides whether an escape is growth or a "
        "regression, so a value nobody can read is not a thing to guess at."
    )


def _planted_caught(expect: str, measured: str) -> bool:
    """Did the scanner do what the entry requires, at plant time?"""
    return _did_catch(measured) == (expect == "caught")


# PLANTED ESCAPING: the reviewer recorded the scanner doing the wrong thing at
# plant time. Allowed growth, derived from the corpus rather than declared.
PLANTED_ESCAPES = {
    name for name, expect, measured, _ in ENTRIES if not _planted_caught(expect, measured)
}
# PLANTED CAUGHT: the scanner did the right thing when the shape arrived. These
# are the ones a regression shows up in, and they are asserted individually.
ASSERTED = [
    (name, expect, src)
    for name, expect, measured, src in ENTRIES
    if _planted_caught(expect, measured)
]


def _planted_by(name: str) -> str:
    """The commit that planted this shape, from `git blame` (CN0).

    Derived, never declared. A provenance string in a map is something the
    implementer can type; a blame line is not.
    """
    import subprocess

    out = subprocess.run(
        ["git", "-C", str(ROOT), "blame", "-L", f"/^id={name}/,+1", "--", str(CORPUS)],
        capture_output=True,
        text=True,
    )
    return out.stdout.split(" ", 1)[0] if out.returncode == 0 and out.stdout else "unknown"


def _misses() -> set[str]:
    """The entries the shipped rule gets wrong, measured over the whole corpus."""
    import tempfile

    out: set[str] = set()
    with tempfile.TemporaryDirectory() as d:
        for name, expect, _measured, src in ENTRIES:
            f = Path(d) / f"test_{name}.py"
            f.write_text(src, encoding="utf-8")
            found = offending(f)
            if (not found) if expect == "caught" else bool(found):
                out.add(name)
    return out


def test_the_corpus_is_not_empty() -> None:
    """Meta-test: an unreadable corpus makes every case below vacuous."""
    assert ENTRIES, f"{CORPUS} parsed to no entries; the format changed"
    kinds = {expect for _, expect, _, _ in ENTRIES}
    assert kinds == {"caught", "exempt"}, (
        f"the corpus asks for {sorted(kinds)}. A corpus with no `exempt` entry "
        "cannot show the hatch still works; one with no `caught` entry cannot "
        "show it is bounded."
    )


def test_every_entry_reaches_the_assertions() -> None:
    """The domain comes from a reader that is not the parser (CO0, R351).

    WHAT THE FLOOR HERE USED TO BE. `assert len(ENTRIES) >= 28`, with a
    message about a parser that silently drops most of them, against a file
    of a hundred and twenty-five. It defended against losing three quarters
    of the corpus and nothing else, and the reviewer walked through it by
    dropping one entry.

    A COUNT IS A FACT ABOUT A FILE I DO NOT WRITE, and it was compared to
    nothing. It is compared to `_headers_in_the_file()` now, which is the
    point: not that the number is large, but that two readers of the same
    file agree about how much of it there is.
    """
    parsed, on_file = len(ENTRIES), _headers_in_the_file()
    assert parsed == on_file, (
        f"{on_file} entry header(s) in {CORPUS.name} and {parsed} reached the "
        "assertions. Something between the file and `ENTRIES` is dropping "
        "entries, and every assertion in this file loses them together -- the "
        "parametrisation, `PLANTED_ESCAPES`, `_measured_misses()` and the "
        "regression test. A shape that is not read cannot regress."
    )

    # AND EVERY ENTRY ROUND-TRIPS, WHICH IS NOT THE SAME AS COMPARING FIELDS
    # (CP0, R365). Two previous versions of this check enumerated what the
    # decision reads and compared those: first the count, then three of the
    # four fields. Both times the next thing the reviewer rewrote was
    # something the enumeration had left out -- the row itself, then the
    # `src` module the scanner is actually run on, which a count and a triple
    # both ignore.
    #
    # An enumeration is a list of what someone thought of. A round trip is
    # not: the parser's own output is put back into the form the file uses
    # and compared to the bytes, so ANY rewrite on the way through fails,
    # including in a field nobody has added yet.
    on_file = _entries_in_the_file()
    assert len(ENTRIES) == len(
        on_file
    ), f"{len(on_file)} entries in the file and {len(ENTRIES)} parsed"
    for parsed, raw in zip(ENTRIES, on_file, strict=True):
        name, expect, measured, src = parsed
        back = (name, expect, measured, src.encode("unicode_escape").decode("ascii"))
        assert back == raw, (
            f"the entry `{raw[0]}` does not survive the round trip. The parser "
            "produced something the file does not say:\n"
            + "\n".join(
                f"  {field}:\n    file  : {r[:200]!r}\n    parsed: {b[:200]!r}"
                for field, r, b in zip(("id", "expect", "measured", "src"), raw, back, strict=True)
                if r != b
            )
        )

    # AND THE TWO DERIVED SETS PARTITION IT. A shape that is in neither is a
    # shape no assertion in this file can fail on, which is the same hole one
    # level down from the parser.
    names = {name for name, _e, _m, _s in ENTRIES}
    covered = {name for name, _e, _s in ASSERTED} | PLANTED_ESCAPES
    assert covered == names, (
        f"{len(names - covered)} entr(y|ies) are in neither the asserted set "
        "nor the recorded escapes, so nothing decides anything about them: "
        f"{sorted(names - covered)}"
    )


@pytest.mark.parametrize("name, expect, src", ASSERTED, ids=[e[0] for e in ASSERTED])
def test_the_exemption_window_gives_the_required_verdict(
    name: str, expect: str, src: str, tmp_path: Path
) -> None:
    f = tmp_path / f"test_{name}.py"
    f.write_text(src, encoding="utf-8")
    found = offending(f)
    if expect == "caught":
        assert found, (
            f"{name}: the entry contains an undeclared tolerance that no marker "
            "legitimately annotates, and the scanner exempted it. The escape "
            "hatch reaches further than the thing it is meant to annotate."
        )
    else:
        assert not found, (
            f"{name}: the marker legitimately annotates the only flaggable node "
            f"and the scanner still reported {found}. A hatch that does not work "
            "gets removed, and then nothing is declared at all."
        )


def _measured_misses() -> set[str]:
    """Every corpus entry the shipped scanner does NOT do what it asks.

    Measured here rather than read off the map: the map is the record, the
    scanner is the fact, and this is the one function that compares them.
    """
    import tempfile

    missed: set[str] = set()
    with tempfile.TemporaryDirectory(prefix="misses-") as tmp:
        for name, expect, _measured, src in ENTRIES:
            f = Path(tmp) / f"test_{name}.py"
            f.write_text(src, encoding="utf-8")
            found = bool(offending(f))
            if (expect == "caught") != found:
                missed.add(name)
    return missed


def test_no_shape_that_was_CAUGHT_when_planted_escapes_now() -> None:
    """A regression, and no string can file it as growth (CN0, R341).

    The domain is every entry the reviewer recorded as doing what it should
    at plant time: the scanner was right about the shape when it arrived. If
    one of them does the wrong thing now, the scanner moved under it.

    NOTHING CAN BE DECLARED TO CLEAR ONE. The field that decides is in a file
    the implementer does not write, and there is no string in this file that
    excuses a name. What CAN still remove a shape from this test is dropping
    it from `ENTRIES`, which is why `test_every_entry_reaches_the_assertions`
    counts the file a second way (R351). The previous version of this
    paragraph said there was nowhere at all, and that was wrong.
    """
    regressions = sorted(_measured_misses() - PLANTED_ESCAPES)
    assert not regressions, (
        f"{len(regressions)} shape(s) the scanner CAUGHT when planted now "
        "escape:\n  "
        + "\n  ".join(f"{n}  (planted at {_planted_by(n)})" for n in regressions)
        + "\nThis is a regression in the scanner, not growth in the corpus. "
        "The corpus records what the shipped rule did at plant time, and "
        "these no longer do it."
    )


def test_improvement_is_visible_and_needs_no_ceremony() -> None:
    """A planted escape that is now CAUGHT is improvement, not a stale record.

    The first version of this asserted the other direction -- that every
    planted escape must still escape -- and it reddened on every shape a rule
    this milestone has tightened. The count is not written here: it moves
    whenever the scanner improves, which is the whole point of the test, and
    a number in a docstring is a figure nothing regenerates (R353). It is
    published in the step report, from `scripts/corpus_figures.py`.
    `measured=` is a PLANT-TIME RECORD, not a claim about today: it says what
    the scanner did when the shape arrived, which is exactly what makes it
    usable as the growth rule's key. Requiring it to stay true would forbid
    the scanner from improving without the reviewer rewriting their own
    corpus, and the asymmetry CN0 asks for is one-directional on purpose.

    What is asserted here is that improvement is REAL and countable, so the
    number appears in the report instead of being assumed.
    """
    improved = PLANTED_ESCAPES - _measured_misses()
    assert len(improved) >= 1, (
        "no shape planted escaping is caught today. Every tightening this "
        "milestone made to the scanner is supposed to show up here, so an "
        "empty set means the corpus and the scanner have stopped touching."
    )


def test_an_undecodable_measured_field_RAISES_rather_than_counting_as_growth() -> None:
    """R350's first half, which CN0 turned from tidiness into a hole.

    `measured != expect` filed a CAUGHT shape as an allowed escape because the
    reviewer's value was a sentence rather than a word. The same shape of
    mistake -- a typo, a new synonym, a value from a later vocabulary -- lands
    on the permissive side every time, which is the wrong side for a field
    that decides whether a regression is allowed.
    """
    assert _did_catch("caught") is True
    assert _did_catch("exempt") is False
    assert _did_catch("clean") is False
    assert _did_catch("caught_but_the_message_is_wrong") is True
    with pytest.raises(ValueError, match="outside the vocabulary"):
        _did_catch("caugth")
    with pytest.raises(ValueError, match="outside the vocabulary"):
        _did_catch("")

    # AND THE ENTRY THAT PROMPTED IT IS ON THE RIGHT SIDE NOW.
    sentence = [name for name, _e, measured, _s in ENTRIES if measured.startswith("caught_but")]
    for name in sentence:
        assert name not in PLANTED_ESCAPES, (
            f"{name} was CAUGHT when planted and is still filed as an allowed "
            "escape, so the decode did not reach the derivation."
        )


def test_the_growth_rule_reads_a_field_the_implementer_cannot_write() -> None:
    """What makes CN0 a check rather than a convention.

    Asserted because the previous version's asymmetry looked identical from
    inside the file and was decided by a string. Two properties: the set of
    allowed escapes comes from the corpus, and the corpus is not writable
    here -- the `PreToolUse` hook refuses it and `docs/SUPERVISOR.md` says so.
    """
    assert PLANTED_ESCAPES, (
        "no entry is recorded as escaping, so the growth rule has no domain "
        "and this file cannot tell growth from regression at all."
    )
    for name in PLANTED_ESCAPES:
        assert any(n == name for n, _, _, _ in ENTRIES), name
    text = CORPUS.read_text(encoding="utf-8")
    assert "measured=" in text, (
        "the corpus no longer carries `measured=`, which is the only field "
        "that distinguishes a regression from growth."
    )
    # R353: THIS WAS `measured == expect`, the bare comparison `7ba1e9d`
    # replaced -- left standing in the one test that certifies the
    # replacement. It disagreed about exactly the entry the decode was
    # written to rescue, the one whose `measured=` is a sentence.
    declared = sum(1 for _, expect, measured, _ in ENTRIES if _planted_caught(expect, measured))
    assert declared, (
        "no entry was CAUGHT when planted, so the regression rule has an "
        "empty domain and nothing this file does can fail for the right "
        "reason."
    )
    # NOT A RATIO. The first version of this asserted that the caught shapes
    # outnumbered the escaping ones, and it reddened -- which is what an
    # adversarial corpus looks like when it is doing its job. What matters is
    # that the regression domain is not empty.
    #
    # THE TWO COUNTS ARE NOT WRITTEN HERE (R353, BP0/BI3). They were, and
    # `7ba1e9d` moved one entry across the boundary the next commit without
    # re-taking either of them -- the same species as R341's second half,
    # in the same file, in the round that repaired it. They are measured by
    # `python scripts/corpus_figures.py`, which runs after every other edit
    # to a revision, and they are published in the step report, which is
    # regenerated by rule. Nothing regenerates a comment.
