"""The single home for every numerical tolerance in FloatFEA.

**This file is deliberately empty of values.** It exists before the first
tolerance does, because a guardrail that arrives after the thing it guards
never takes: by then tolerances have already been scattered into call sites and
default arguments, and consolidating them becomes a refactor nobody schedules.

---

## The rule

Every numerical tolerance in this repository lives here. No exceptions, no
local literals, no default arguments carrying a tolerance. This includes
anything that functions as a tolerance under another name -- convergence
thresholds, comparison epsilons, "small number" guards, tier cutoffs in
screening, and any factor introduced to make two numbers agree.

Do not modify this file to make a failing test pass. If a test fails, the
default hypothesis is that the code is wrong, not that the tolerance is tight.

Changing a value requires a written justification in the milestone closure
artifact (`docs/closure/F<n>.md`) naming the physical or numerical reason the
previous value was incorrect. A tolerance change in the same commit as the code
change it rescues will be rejected in review.

See `CLAUDE.md` sec. Tolerances and `WORKFLOW.md` sec. "The one habit that
matters most".

---

## Two classes, and the counter-case rule binds on only one (AO2)

Every entry is **STRUCTURAL** or **ACCURACY**, and the distinction is declared in
its comment because a rule applied where it does not fit gets weakened to
accommodate.

**STRUCTURAL** — a threshold on a physical or numerical *condition*, which fires
by design when the condition holds. `MEMBER_ORIENTATION_DEGENERACY` fires on the
platform's vertical spars on purpose; it exists to force an explicit choice, not
to be tuned until it stops firing. Demanding a "smallest defect it must still
catch" of such an entry would force an artificial number.

**ACCURACY** — a ceiling on a residual or error that is *supposed* to be small.
These are the ones "the test fails, widen the tolerance" can reach, and they carry
a **paired counter-case**:

    X          = <ceiling the check asserts>
    X_COUNTER  = <smallest defect that must still fail>

A counter comes in two kinds and they are not interchangeable (BG1):

* `X_COUNTER` is a **response magnitude**, in the assertion's own quantity, and
  it must sit above the ceiling -- so widening `X` toward it eventually breaks a
  test.
* `X_COUNTER_DEFECT` is a **defect size**: the perturbation that must still be
  caught. It is used where the ceiling is not a constant, so no ordering between
  the two numbers exists to check. It carries a stronger obligation instead:
  a test injects it and asserts the shipped assertion FIRES.

The second kind exists because the first can be inert. `RESULTANT_EXACTNESS`
could be widened 680x in silence, because its only guard was `ceiling < counter`
-- a comparison between two literals in this file, with nothing running the
defect. **A counter that nothing injects is a number, not a check.**

**And nothing else.** An `X_MEASURED` -- the worst value seen at the entry's
sites -- lived here briefly (BD1) and was removed (BE2). A hand-written literal
in this file, compared against two other hand-written literals in this file, is
a check whose subject the check itself supplies: four of the nine were wrong on
arrival, two of them measured on a solve path that had been deleted one commit
earlier, and no test could tell. **Measured values belong in the step report,
generated by the run at the report's own commit.** What lives here is the
ceiling, the counter-case, and where the justification is written down.

The pairing is what makes the ceiling an execution result rather than a
reviewer's judgement:

* **existence is mechanically checkable** — every `X` has an `X_COUNTER`;
* **it cannot be satisfied by prose**, because `X_COUNTER` is a number an
  executable test consumes;
* **widening `X` toward `X_COUNTER` eventually breaks the counter-test.**

That last property is the point. A tolerance with a floor but no ceiling can
always be widened one more order and still look principled.


## The comment convention

Every entry carries four things, and a reviewer should be able to check the
value without reading any other file:

1. the **gate** it serves (G2.1, G4.1, ...) and the verification case (V1.1,
   V4.5, ...) from `docs/verification/README.md`;
2. **what is being compared** -- absolute or relative, and to what reference;
3. the **physical or numerical reason** the value is what it is, not merely that
   it passes;
4. the **date and milestone** it was last changed under.

Template::

    # G<n.n> / V<n.n> -- <what is compared, absolute or relative>
    # Reason: <physical or numerical basis for this magnitude>
    # Set: <YYYY-MM-DD>, <milestone>
    NAME: Final[float] = <value>

A value whose comment says only "empirically determined" or "matches the
reference" is not documented; it is a fudge factor with better manners.

---

## Layout

Entries are grouped by verification-ladder rung, so that a reviewer reading a
red test at rung 1 sees rung 1's tolerances together and is not invited to
compare them against rung 5's, which answer a different kind of question.

Rungs are defined in `docs/verification/README.md`.
"""

from __future__ import annotations

from typing import Final

# ---------------------------------------------------------------------------
# Model construction -- geometric degeneracy guards
#
# Not tied to a verification rung: these guard the construction of the model
# itself, and they fail loudly at build time rather than producing a wrong
# number at solve time.
# ---------------------------------------------------------------------------

# CLASS: STRUCTURAL -- fires by design on vertical members; no counter-case.
# G0.2 / docs/conventions.md sec. "Member local axes" -- minimum |z_hat x x_hat|
# for the DEFAULT global-Z orientation reference to be admissible on a member.
# Dimensionless; equals the sine of the member's angle from vertical.
#
# Compared: the magnitude of the cross product used to build local y, against
# this floor. Below it the model builder RAISES and demands an explicit
# orientation node or roll angle. It does not fall back to another axis.
#
# Reason: local y is built from z_hat x x_hat, so its direction error amplifies
# any perturbation in the member axis by 1/|z_hat x x_hat|. The construction is
# exactly singular at vertical and ill-conditioned near it. 0.05 corresponds to
# 2.87 deg from vertical and bounds that amplification at 20x. The spars in this
# platform are vertical, so this guard fires on the real model by design -- it
# exists to force an explicit choice, not to be tuned until it stops firing.
# Raising it excludes valid members; lowering it admits members whose section
# axes are not reliably oriented.
# Set: 2026-08-10, F0
MEMBER_ORIENTATION_DEGENERACY: Final[float] = 0.05


# CLASS: STRUCTURAL -- a modelling admission limit. It fires by design on parts
# that are not beams, and it exists to force an explicit choice (an F7 shell
# sub-model), not to be tuned until it stops firing. No counter-case, per AO2.
#
# BH0 / docs/milestones/F2.md sec. 5b, Q5 -- the smallest member length-to-depth
# ratio for which a Timoshenko beam element is an admissible model.
# Dimensionless: member length over the OUTER DIAMETER,
#
#     D_o = 2 sqrt( 2 I / A  +  A / (2 pi) )
#
# which is what `_outer_diameter` computes. This entry used to give
# `D = 4 sqrt(I/A)`, the solid-circle relation the code records as a rejected
# first draft: on the gate's own section it returns 0.8317 m against the true
# 0.600 m, a factor of 1.3862, so every ratio derived from it was 28% low
# (R87). The limit is NOT in `docs/conventions.md` -- that file is F0-locked
# and a new section there needs an F0 reopen commit.
#
# ON THE MEMBER, NOT THE ELEMENT, and that was measured rather than assumed. The
# gate's own mesh has a member at L/D = 16.12 and two of its five elements at
# L/D = 1.32 and 1.50, so an element-wise limit of 2 would reject the patch
# test's own model. Beam validity is a property of the physical member;
# subdividing it is ordinary practice and changes nothing.
#
# Reason for 2.0: shear-flexible beam kinematics still assume plane sections and
# a length over which stresses redistribute, and below L/D ~ 2 there is no such
# length. The value is a MODELLING JUDGEMENT, proposed by the supervisor and
# CONFIRMED BY XABIER on 2026-09-06 (F2.md sec. 5b, Q5) -- it is not derived from
# a measurement here, and it is written down as a judgement rather than dressed
# as one.
#
# THE MEASUREMENT THAT USED TO SUPPORT IT IS WITHDRAWN, AND THE JUDGEMENT NOW
# STANDS ALONE. This entry carried a sweep showing the gate's negative control
# FAILING below L/D = 2, and that was a property of the SOLVED nodal field error,
# which G2.2 no longer asserts. Re-measured on the quantity that ships, the
# control does NOT fail below the limit -- it is STRONGER there, because the
# response falls with slenderness. The single number: at the limit itself the
# 1e-6 single-element defect responds at 1.14e-09, which is 11371x the counter.
# The sweep it comes from is in docs/reports/F2/step-4.md, revision 10 sec. 4.
#
# THE TABLE IS NOT HERE, AND THAT IS BI3 (added 8d6ba7d, violated two commits
# later by this very entry -- R92). No committed script regenerates it, so it
# belongs in the report, which is regenerated by rule, and this entry carries the
# one number it needs and a pointer.
#
# So the limit keeps its physical justification and loses its numerical one, and
# that is recorded rather than papered over: nothing in this repository now
# measures a cost to analysing an L/D = 1 stub as a beam. The reason to refuse it
# is that beam kinematics do not describe it, which is a statement about the
# model and not about round-off.
# Set: 2026-09-04, F2. Support re-measured and withdrawn 2026-09-06, F2
BEAM_ADMISSION_L_OVER_D: Final[float] = 2.0


# CLASS: STRUCTURAL -- a condition (is this DOF alive?), not an error ceiling.
# G1.6 / diagnostics -- floor below which a DOF carries no signal and MUST NOT
# enter any aggregate statistic. Relative, against the largest reference
# magnitude across the DOF being aggregated.
#
# Compared: each DOF's reference magnitude (|mu|, |B|, whatever the statistic is
# formed over) divided by the maximum over that same set, against this floor.
# Below it the DOF is structurally dead and `frames.live_dof` excludes it.
#
# Reason: a body of revolution has no yaw radiation, so yaw `mu` on this platform
# is 1.2e-17 against 4.2e-01 in surge -- a ratio of 3e-17, which is round-off, not
# a small physical quantity. Including such a DOF in a correlation or a norm
# computes a statistic over noise and reports it as a measurement; it did exactly
# that once, moving an AG5 correlation from +0.53 to +0.65. The floor sits at
# 1e-12 because double precision gives ~1e-16 relative and four orders of headroom
# separates "accumulated round-off" from "small but real": the smallest genuinely
# physical ratio measured on this platform is heave's 0.01x, twelve orders above.
# Raising it would begin discarding real DOF; lowering it re-admits round-off.
# Set: 2026-08-26, F1
DEAD_DOF_RELATIVE_FLOOR: Final[float] = 1e-12


# CLASS: STRUCTURAL -- a condition (is this reference admissible here?).
# G1.6 / diagnostics -- tolerance at or below which an INTERPOLATED reference is
# inadmissible and `frames.assert_reference_supports` refuses the comparison.
# Relative, same units as the comparison tolerance it is checked against.
#
# Compared: the tolerance a comparison intends to assert at, against this floor.
# At or below it the reference must come from a solved/exact point, not from
# interpolation between grid points.
#
# Reason: interpolating a reference across a grid gap injects an error set by how
# much the quantity varies over that gap, and it is invisible in the result. The
# measured case: omega = 2.000377 sits at 48.6% of the gap 1.930166 -> 2.074677 --
# dead centre, because case frequencies are chosen for physics, not grid alignment
# -- and B varies ~60% across it. That produced a residual of 5.914e-04 against a
# true reconstruction error of 1.359e-15: ELEVEN orders, entirely from the
# interpolation. 1e-3 sits just above the measured 5.9e-4 artifact, so a
# comparison asserting at or below it cannot distinguish its own interpolation
# from the thing it is measuring. Raising it would admit interpolated references
# into comparisons the artifact dominates; lowering it below ~6e-4 would admit the
# exact case already measured to fail.
# Set: 2026-08-27, F1
INTERPOLATED_REFERENCE_TOLERANCE_FLOOR: Final[float] = 1e-3


# CLASS: ACCURACY -- carries PANEL_RECONSTRUCTION_RESIDUAL_COUNTER below.
# G1.6 / V4.6 -- ceiling on the panel-reconstruction residual
# ||R - T||_F / ||T||_F, where R integrates the exported per-panel radiation
# pressure over each body's panels and T is w^2*A + i*w*B from the same BEM solve.
# Relative, Frobenius, dimensionless.
#
# Reason: the identity is EXACT in exact arithmetic -- both sides are the same
# surface integral, one evaluated panel-wise and one by the solver -- so the only
# admissible residual is floating-point accumulation. Measured 1.308e-15 on the
# 12-buoy platform (10,560 panels, 72 DOF) and 1.518e-16 on the committed
# 64-panel fixture. 1e-12 sits ~3 orders above the larger of those, which covers
# BLAS/platform variation in the einsum reduction without admitting anything
# physical: the smallest deliberate defect measured -- ONE panel of 10,560 with
# its area perturbed by 1% -- produced 1.082e-05, seven orders ABOVE this ceiling.
# Raising it toward 1e-5 would begin admitting real geometry errors; lowering it
# to ~1e-15 would make the gate sensitive to summation order.
# Set: 2026-08-28, F1
PANEL_RECONSTRUCTION_RESIDUAL: Final[float] = 1e-12

# COUNTER-CASE for the above -- the smallest defect the gate must still fail.
# Measured, not chosen: ONE panel of the 10,560-panel platform mesh with its
# area perturbed by 1% produces a residual of 1.082e-05. The counter-test
# asserts a perturbed fixture exceeds this value, so widening
# PANEL_RECONSTRUCTION_RESIDUAL toward it eventually makes that test fail --
# which is the property that makes the ceiling defensible by execution rather
# than by argument. Seven orders separate the two.
# Set: 2026-08-30, F1
PANEL_RECONSTRUCTION_RESIDUAL_COUNTER: Final[float] = 1.0e-5


# ---------------------------------------------------------------------------
# Rung 1 -- The solver is a solver
# Rigid-body modes (G2.1/V1.1), patch test (G2.2/V1.2), unit scaling (G2.5/V1.3).
# These compare against exact algebraic results, so tolerances here are set by
# floating-point accumulation and conditioning, never by physical judgement.
# ---------------------------------------------------------------------------

# CLASS: ACCURACY -- carries RIGID_MODE_EXACTNESS_COUNTER_DEFECT below.
# G2.1 / V1.1, THE RESIDUAL FORM (Q7). The worst over the six analytic
# rigid-body vectors of `||K v|| / (max|K| * ||v||)`: how far the exact
# rigid-body motions are from the nullspace of the assembled matrix.
#
# WHY THIS RATHER THAN THE EIGENVALUE RATIO. `RIGID_BODY_MODE_RATIO` below
# compares the sixth eigenvalue with the seventh, and the reviewer's corpus of
# twenty-eight frames showed what that measures: a large minority of them
# exceed its ceiling with a DEFECT-FREE element -- the count is
# `{{fig:retired_ratio_over_ceiling_on_corpus}}`, regenerated rather than
# written here, because `sixteen` stood in this sentence and the same round's
# own render said ten (R395). The quantity moves with the frame's
# conditioning -- bracing sections, mesh subdivision, span, and above
# all the length unit. The residual form does not. It reads `K` and the
# analytic vectors and nothing else, and it needs no eigensolver, so there is
# no starting vector and nothing to pin.
#
# Reason for 1e-15: measured over every entry in
# `tests/corpus/g21_rigid_body_frames.txt`, which is the reviewer's file and
# not mine, and published by name in the step report. The worst configuration
# sits an order below this ceiling, and the spread across the corpus is the
# unit system rather than the element.
# Set: 2026-09-13, F2
RIGID_MODE_EXACTNESS: Final[float] = 1e-15

# COUNTER-CASE, INJECTED into the assembled matrix and run through the gate.
# Reason for 1.0e-14: a diagonal stiffness resisting a rigid translation at
# this size takes the residual to `4.4841e-15`, against a ceiling of `1e-15`.
# The detection edge, solved by bisection rather than read off a sweep, is
# `2.2038e-15`, so the counter sits `4.54x` past it.
#
# `about 5e-14` STOOD HERE AND WAS WRONG BY A DECADE (R394). It was the
# response to a defect ten times larger, written from a sweep row rather than
# from the shipped `counter_response("residual")`, and the entry that carried
# it also claimed the counter was clear of its edge without ever solving the
# edge. Both numbers here are the shipped function's, at this commit.
# Set: 2026-09-13, F2; figures re-taken 2026-09-14
RIGID_MODE_EXACTNESS_COUNTER_DEFECT: Final[float] = 1.0e-14

# CLASS: ACCURACY -- carries RIGID_MODE_FLOOR_COUNTER_DEFECT below.
# G2.1 / V1.1, THE COUNT (Q7 as CS0 states it). On the same homogenised matrix
# the residual uses -- `K_hat = K / max|K|` -- the numerically-zero threshold is
#
#     tau = RIGID_MODE_FLOOR * ||K_hat|| * eps
#
# and the count is how many eigenvalues of `K_hat` fall below `tau`. That count
# is asserted equal to six. This entry is the multiplier: how many units of the
# matrix's own round-off an eigenvalue may carry and still be zero.
#
# THE FIRST VERSION COUNTED "MODES BELOW THE LARGEST GAP" AND THAT IS NOT A
# COUNT. The largest gap in a spectrum can sit anywhere, and at a length unit
# one decade finer than the corpus's kilometre entry it sat after the
# EIGHTEENTH mode -- returning eighteen, with a gap eighteen times above its
# own floor, so nothing warned (R397). A count has to be below a threshold;
# the gap is the validity condition ON that count and is asserted separately.
#
# Reason for 10: measured over all fifty-six frames in
# `tests/corpus/g21_rigid_body_frames.txt`, which is the reviewer's file. At
# this value the count is six at every one. At 1 it is five at two of them --
# a genuine rigid mode carrying slightly more than one unit of round-off -- and
# at 100 and above it picks up a flexible mode on the worst-conditioned frames.
# The window is a decade wide on each side and this sits in it.
# Set: 2026-09-14, F2
RIGID_MODE_FLOOR: Final[float] = 10.0

# COUNTER-CASE, INJECTED into the assembled matrix and run through the gate.
# Reason for 1.0e-12: a diagonal stiffness resisting one rigid translation at
# this size lifts that mode above `tau`, so the count reads FIVE and the gate
# reddens on the count itself. Smaller sizes leave it below: the crossing is
# between `1e-14` and `1e-12` of the largest entry, and this sits clear of it
# rather than on it. The sweep is in the step report (BI3).
# Set: 2026-09-14, F2
RIGID_MODE_FLOOR_COUNTER_DEFECT: Final[float] = 1.0e-12

# CLASS: ACCURACY -- carries RIGID_MODE_GAP_COUNTER_DEFECT below.
# G2.1 / V1.1, THE VALIDITY OF THE COUNT (Q7 as CS0 states it). The separation
# between the last eigenvalue below `tau` and the first above it, IN ORDERS OF
# MAGNITUDE -- `log10(first_above / last_below)`.
#
# WHAT IT IS FOR, and it is not the count. A count read across a boundary that
# is barely there is a coin toss dressed as a measurement, so when this fails
# the test says the count is UNTRUSTWORTHY at this configuration and goes red.
# It never returns a number it does not believe.
#
# Reason for 1.3 orders, and this value is BRACKETED ON BOTH SIDES by
# measurement rather than chosen for room:
#
#   above  the smallest separation over the fifty-six corpus frames is
#          `2.071` orders on the canonical machine, at the thousand-kilometre
#          re-expression. Q8's floor class requires a floor-class decision to
#          survive the declared platform spread of `1.5x`, and `2.071 / 1.3`
#          is `1.59x`. At `1.5` it was `1.38x` and `--check` refused it --
#          correctly, since the platform alone could then carry the decision.
#   below  the narrowest separation this frame can be made to produce WITH THE
#          COUNT STILL AT SIX is `1.125` orders, measured by scanning the
#          counter's own parameter. Below `tau` the mode joins the nullspace
#          and the COUNT moves instead, which is a different assertion.
#
# So the window is `(1.125, 1.381)` and this sits inside it. THAT IS THE
# TIGHTEST BRACKET OF ANY ENTRY IN THIS FILE, and the reason is physical: the
# separation cannot be squeezed below the distance from the sixth eigenvalue
# up to `tau`, and `tau` is fixed by `RIGID_MODE_FLOOR`, which the corpus
# fixes. Both margins are published by name in the step report.
# Set: 2026-09-14, F2
RIGID_MODE_GAP: Final[float] = 1.3

# COUNTER-CASE, INJECTED into the assembled matrix and run through the gate.
# Reason for 8.318e-15: a connection that is NEARLY released. The torsional
# continuity of one member is cut and then given back a stiffness of this size
# relative to the largest entry, which puts the seventh mode just above `tau`:
# the count still reads six -- the right answer -- and the separation collapses
# to `1.125` orders, a factor of `1.50` narrower than the floor allows. That is
# precisely the state this entry exists to refuse.
#
# IT IS NEAR ITS OWN EDGE AND THAT IS NOT CARELESSNESS. The value is the
# minimum of a scan over the injection's own parameter: no size produces a
# narrower separation at count six, because below `tau` the mode joins the
# nullspace and the COUNT moves instead. A counter cannot be placed further
# from an edge than the quantity can reach.
# Set: 2026-09-14, F2
RIGID_MODE_GAP_COUNTER_DEFECT: Final[float] = 8.318e-15

# CLASS: ACCURACY -- carries RIGID_BODY_MODE_RATIO_COUNTER_DEFECT below.
# G2.1 / V1.1 -- the sixth eigenvalue of an unconstrained stiffness matrix,
# divided by the seventh. Dimensionless BY CONSTRUCTION, and that is the gate's
# own wording rather than a convenience: the eigenvalues of `K` carry units and
# scale with `E`, with the section and with the mesh, so a ceiling on them would
# be a ceiling on the model. The ratio is invariant under all three.
#
# Reason for 1e-12: measured at the shipped frame -- see `rigid_body_mode_ratio`
# in docs/milestones/F2_figures.md, which is the number this entry is checked
# against and is not retyped here (R194). That leaves about 83x of headroom ON
# THE CANONICAL MACHINE.
#
# `62x` STOOD HERE AND IS WITHDRAWN (BP0). It was taken from a laptop render,
# where the ratio is 1.34x larger; the same code on the machine Q8 makes
# canonical gives 83x. Neither number is wrong about its own machine and the
# ceiling is unaffected either way -- this is a ratio of two eigenvalues at
# 1e-14, where the numerator is round-off, and Q8's third class exists because
# figures of that shape disagree between machines by O(1) factors. The canonical
# one is the one this entry means.
#
# WHAT IT CATCHES, measured rather than asserted. The response is linear in the
# defect over eight decades: a diagonal stiffness resisting a rigid translation,
# as a fraction of the largest matrix entry, gives
#
#     1e-14 -> 3.03e-13     1e-12 -> 3.06e-11     1e-8 -> 3.06e-07
#
# so this ceiling is crossed by a defect somewhere between `1e-14` and `1e-13` of
# the largest entry. The sweep is in the step report, which is regenerated by
# rule; it is not tabulated here (BI3).
# Set: 2026-09-09, F2
RIGID_BODY_MODE_RATIO: Final[float] = 1e-12

# COUNTER-CASE, INJECTED into the assembled matrix and run through the gate.
# Reason for 1.0e-12: a defect one decade above the crossing measured above,
# which takes the ratio to `3.06e-11` -- about 31x past the ceiling. It is
# deliberately NOT the smallest size that reddens: a counter sitting on its own
# detection edge tests the edge rather than the gate, and the edge is published
# in the step report where it can be re-measured.
# Set: 2026-09-09, F2
RIGID_BODY_MODE_RATIO_COUNTER_DEFECT: Final[float] = 1.0e-12

# CLASS: ACCURACY -- carries RIGID_BODY_SUBSPACE_LOSS_COUNTER_DEFECT below.
# G2.1 / V1.1 -- the largest fraction of an analytic rigid-body vector left
# outside the span of the six computed zero-energy modes. A fraction in [0, 1],
# so dimensionless, and invariant under scaling either the analytic vector or the
# computed basis.
#
# THIS IS THE ASSERTION AP3 SAYS IS THE REAL CONTENT, and the eigenvalue ratio
# above is the weaker half. Inside the six-fold degenerate zero eigenvalue the
# eigenvectors are an arbitrary basis -- non-unique in principle -- so a test on
# mode shapes asserts what the mathematics does not confer. Membership of the
# SPAN is invariant under every basis choice in that block.
#
# Reason for 1e-13: measured at the shipped frame the clean loss is `5.306e-15`
# -- `rigid_body_subspace_loss` in the generated figures -- so about 19x of
# headroom. Tighter than the ratio's ceiling because the quantity is a normalised
# projection residual rather than a ratio of two eigenvalues, and it accumulates
# less: the same defect sweep moves it from `7.59e-14` at `1e-14` to `7.47e-12`
# at `1e-12`.
#
# ASSERTED ON THE WORST OF THE SIX, NEVER ON A MEAN (`CLAUDE.md` sec.
# Non-negotiables). One lost direction beside five good ones is exactly the
# failure this exists to catch.
# Set: 2026-09-09, F2
RIGID_BODY_SUBSPACE_LOSS: Final[float] = 1e-13

# COUNTER-CASE, INJECTED into the assembled matrix and run through the gate.
# Reason for 1.0e-12: the same injected defect as the ratio's counter, which is
# the point -- one defect must redden both halves of G2.1, because a stiffness
# that resists a rigid translation both lifts a zero eigenvalue and removes that
# translation from the span. It takes the loss to `7.47e-12`, about 75x past the
# ceiling.
# Set: 2026-09-09, F2
RIGID_BODY_SUBSPACE_LOSS_COUNTER_DEFECT: Final[float] = 1.0e-12

# CLASS: ACCURACY -- carries TRANSFORM_INVARIANCE_COUNTER below.
# G2.5 / V2.4 -- agreement between the rotated response and the rotated local
# response. RELATIVE AND DIMENSIONLESS, scaled by the response itself:
#
#     |u_global - R u_local|  <=  TRANSFORM_INVARIANCE * ||u_local||_inf
#
# Reason: an orthogonal transform cannot change the response, so this is exact in
# exact arithmetic and the only admissible discrepancy is accumulation through a
# 12x12 triple product and a 6x6 solve. Measured worst-case over all six load
# DOF: 3.836e-15. 1e-11 sits ~4 orders above that floor.
#
# THE FORM MATTERS AS MUCH AS THE VALUE (AW1). An earlier draft used an ABSOLUTE
# atol on a displacement, which is a dimensional quantity: posing the same problem
# in millimetres moves the round-off floor by three orders while the tolerance
# stays put, so V1.3 (unit scaling) would either fail on this assertion or pass it
# vacuously. The offending component's exact value is also ZERO, where no absolute
# floor is meaningful at all -- which is why the first draft's 1e-18 failed against
# a measured 1.07e-18 for reasons unrelated to the transform. Scaling to
# ||u_local||_inf handles the zero components by the scale rather than by a floor.
# Set: 2026-09-02, F2
TRANSFORM_INVARIANCE: Final[float] = 1e-11

# COUNTER-CASE, measured IN THE SAME QUANTITY as the assertion (AW1).
# A _COUNTER is the smallest defect the SAME assertion detects, so it is measured
# on the displacement residual, not on the spectrum. Perturbing the correct
# rotation by the non-orthogonal I + [theta x] map gives a residual linear in
# theta: 1.227e-02 at 1e-3 rad, 1.228e-05 at 1e-6, 1.228e-07 at 1e-8. The
# counter is set at the last of these, so the gate must catch a non-orthogonality
# of TEN NANORADIANS -- four orders above the ceiling, and far below any
# first-order-rotation bug a real model could contain.
# Set: 2026-09-02, F2
TRANSFORM_INVARIANCE_COUNTER: Final[float] = 1.2e-7


# CLASS: ACCURACY -- carries TRANSFORM_SPECTRUM_INVARIANCE_COUNTER below.
# G2.5 / V2.4 -- relative agreement between eig(T^T K T) and eig(K), scaled by the
# largest eigenvalue. A separate entry from TRANSFORM_INVARIANCE because it is a
# DIFFERENT QUANTITY: the spectrum test is the only one that detects a
# non-orthogonal T without reference to any particular load case.
#
# Reason: an orthogonal similarity preserves eigenvalues identically. Measured
# shift under the real transform: 2.71e-16. 1e-11 sits ~5 orders above it.
# Set: 2026-09-02, F2
TRANSFORM_SPECTRUM_INVARIANCE: Final[float] = 1e-11

# COUNTER-CASE for the spectrum test, measured on the spectrum.
# The I + [theta x] trap shifts the spectrum by 1.30e-03 at theta = 0.05 rad,
# 5.20e-05 at 0.01, and 5.20e-07 at 0.001 -- so the gate must catch a first-order
# rotation of a milliradian.
# Set: 2026-09-02, F2
TRANSFORM_SPECTRUM_INVARIANCE_COUNTER: Final[float] = 5.0e-7


# CLASS: ACCURACY -- carries SUBDIVISION_INVARIANCE_COUNTER below.
# G2.2 / V1.2 -- relative agreement of a fixed-length cantilever's tip response
# across element counts. Dimensionless (a ratio of like quantities).
#
# Reason: the element is NODALLY EXACT for constant section and load, so
# subdividing changes nothing but round-off. Measured deviation from the
# one-element result: 9.99e-15 at n=2, 1.16e-14 at n=5, 4.58e-13 at n=11 -- and
# the per-solve equilibrium residual grows with it, 1.38e-14 to 8.79e-13 over the
# same range. That growth is a CONDITIONING signature, not a formulation error:
# more DOF means a longer factorisation chain. 1e-11 sits ~20x above the worst
# measured deviation, which leaves room for that growth at the mesh sizes F3 will
# use without admitting anything structural.
#
# DECLARED LATE (AW2). This value existed as an undeclared `rtol=1e-10` literal
# inside the test before it was measured, which is the local-literal failure this
# file exists to prevent.
# Set: 2026-09-02, F2
SUBDIVISION_INVARIANCE: Final[float] = 1e-11

# COUNTER-CASE, measured on the same quantity.
# A relative stiffness error in ONE member of the chain produces a tip deviation
# linear in it: 4.84e-04 at 1e-3, 4.85e-06 at 1e-5, 4.85e-08 at 1e-7. The counter
# is set at the last, so the gate must catch a one-part-in-10^7 error in a single
# element -- three orders above the ceiling.
# Set: 2026-09-02, F2
SUBDIVISION_INVARIANCE_COUNTER: Final[float] = 4.8e-8


# CLASS: ACCURACY -- carries PATCH_TEST_EXACTNESS_COUNTER_DEFECT below.
# G2.2 / V1.2 -- the INTERIOR OUT-OF-BALANCE OF THE EXACT FIELD. With
# `D = diag(I3, l I3)` per node, `w = D u_exact`, `K_hat = D^-1 K D^-1`:
#
#     max |(K_hat w)[interior]| / (max|K_hat| * max|w|)
#
# Dimensionless, and homogeneous -- rotations weighted by a characteristic
# length, so metres are never divided by radians (R2, applied to the matrix as
# well as the field).
#
# Reason: Irons' test says the exact constant-strain field SATISFIES the discrete
# equations. That is checkable without solving anything, and the quantity has no
# factorisation in it: numerator and denominator both carry the largest
# stiffness, so `cond` cannot enter and the `lambda^2` amplification that comes
# from measuring a bending displacement against axial round-off cannot arise.
#
# THIS REPLACES THE SOLVED NODAL FIELD ERROR, AND THE REPLACEMENT IS THE ROUND'S
# WHOLE FINDING (F2.md sec. 5b, Q6). That quantity is the FORWARD error of a
# linear solve -- `cond` x backward error -- and five successive attempts to bound
# it with a constant, a conditioning-scaled ceiling, an equilibrated floor and a
# validated domain were each refuted by one more axis the envelope had not
# spanned: unit system, member lambda, mesh at fixed lambda, orientation, roll,
# and finally section size at fixed lambda. It is now reported per corpus entry
# and asserted nowhere. `PATCH_TEST_ROUNDOFF`, its counter and
# `G22_VALIDATED_MEMBER_LAMBDA` were removed with it -- the second tier existed to
# relieve entries this quantity does not strain.
#
# WHY 5e-15 AND NOT THE 1e-12 THIS ENTRY CARRIED. A ceiling derived for one
# quantity does not transfer to another; keeping the number would be R41's
# species. The new quantity's live band is 577x wide, and AT 1e-12 THE COUNTER
# SITS BELOW THE CEILING -- a 1e-6 single-element defect on the corpus's most
# slender entry would not be caught (margin 0.11x). 5e-15 is the geometric centre
# of the band, 4.47e-15 rounded up. It is a TIGHTENING by 200x.
#
# THOSE ARE THE DERIVATION'S NUMBERS AND THEY ARE HISTORY (R208). At the
# derivation, 2026-09-06, the band was 577x wide and 5e-15 sat 26.8x above the
# worst clean entry and 21.5x below the smallest asserted defect response. Both
# were written here in the PRESENT tense and both were false within two corpus
# rounds. What the value must satisfy is checked live and generated:
# `clean_worst_ratio` below one, and every `margin_<defect>` row for the asserted
# defects above it, in docs/milestones/F2_figures.md.
#
# THE ROUND THAT FIXED R208 TYPED A THIRD FIGURE INTO THIS PARAGRAPH AND DATED
# THE DERIVATION WRONG (R212). It read "the clean side alone moved to 10.2x",
# already two corpus rounds behind when it was written, and `2026-09-05` against
# this entry's own footer of `2026-09-06`. Recorded because a commit whose whole
# subject is not typing figures typed one.
#
# THE FLOOR AND EVERY DEFECT'S MARGIN are regenerated by the shipped corpus runner
# and tabulated in the newest revision of docs/reports/F2/step-4.md (BI3: a table
# in this file is produced by a script at its own commit or it is not in this
# file, and that mechanism is step 4a's; the figures themselves are generated
# into docs/milestones/F2_figures.md). The worst clean value over the corpus is
# `clean_worst_ratio` there, and it is cited rather than typed for the reason
# two lines of this entry demonstrated (R208).
#
# EVERY DEFECT'S RESPONSE FALLS AS 1/lambda_weak^2, and this ceiling is what it is
# compared against. The residual normalises by the largest stiffness -- the axial
# one -- so a defect in a bending block is measured against a quantity it does not
# enter; the fall-off is BK's mechanism and it applies to structural defects and
# small ones alike, at a measured exponent of -1.99 for both. That is why the
# counter-case is an INJECTED DEFECT and the comparison is to THIS value, not to a
# floor on the response (BO0): a response of 3.5e-06 at `L/r_min = 2885` is nine
# orders of detection, and the form that called it undetectable was comparing it
# to 3.5e-05.
#
# THIS IS AN EXACTNESS TOLERANCE, NOT A CONVERGENCE ONE. An element that
# reproduces constant curvature only in the limit is passing a convergence test
# wearing the patch test's clothes; there is nothing between exact and wrong here,
# which is why the value sits at ULP scale rather than at an engineering one.
# Set: 2026-09-02, F2. Quantity and value REPLACED 2026-09-06, F2.
PATCH_TEST_EXACTNESS: Final[float] = 5e-15

# COUNTER-CASE, AND IT IS A DEFECT SIZE RATHER THAN A RESPONSE FLOOR (BO0).
# The size of the single-element stiffness error injected into the patch test.
# Relative, dimensionless. The assertion it serves is NOT a comparison against
# this number: the test injects a defect of this size and requires
#
#     response > PATCH_TEST_EXACTNESS
#
# -- the gate goes red -- and the margin `response / ceiling` is recorded per
# entry with its operating point and asserted against nothing.
#
# THE FORM THIS REPLACES WAS WRONG FOR SIX ROUNDS UNDER THREE NUMBERS. `1.0e-7`,
# `1.0e-13` and `3.5e-05` were each called a counter while functioning as a floor
# on the RESPONSE, so an entry "failed to detect" whenever its response fell
# below a constant rather than below the ceiling. At `L/r_min = 2885` the
# wrong-DOF defect responds at `3.5e-06` against a ceiling of `5e-15`: nine
# orders of detection, reported as a wall because the comparison was to `3.5e-05`.
# Every "undetectable" corpus entry since R94 was that artefact.
#
# AND THE FALL-OFF APPLIES TO EVERY DEFECT, NOT TO SMALL ONES. The residual
# normalises by the largest stiffness -- the axial one -- so any defect in a
# bending block falls as `1/lambda_weak^2`. Measured, both structural defects
# fall at exponent `-1.99`, the small defect's own, with
# `wrong_dof / 1e-6-defect` constant at `8.8e+08` across the family. The claim
# that structural defects are `O(1)` and do not fall is WITHDRAWN. It stops
# mattering once the comparison is to the ceiling.
#
# Reason for 1e-6: it is small enough to be a plausible slip -- a length or a
# section wrong in the sixth digit -- and the gate still reddens on it at every
# entry in the corpus -- see `margin_one_element_scaled` in the generated
# figures rather than a number typed here (R176). The
# per-entry margins are regenerated by the shipped corpus runner and tabulated in
# docs/reports/F2/step-4.md (BI3).
#
# Set: 2026-09-06, F2. Named `_COUNTER_DEFECT` because it is a defect size and
# orders against nothing in the ceiling's quantity (AO2).
PATCH_TEST_EXACTNESS_COUNTER_DEFECT: Final[float] = 1.0e-6

# CLASS: STRUCTURAL -- the guard on the line above, and it exists because that
# line had none. No counter-case of its own, per AO2: it is a bound on how far a
# defect SIZE may sit above the smallest one the gate can still catch.
#
# G2.2 / V1.2 -- `PATCH_TEST_EXACTNESS_COUNTER_DEFECT` must satisfy
#
#     COUNTER_DEFECT  <=  PATCH_TEST_COUNTER_HEADROOM  x  edge
#
# where `edge` is the smallest single-element defect the gate still reddens on,
# bisected on EVERY solved corpus entry under the gate's own rule (worst state)
# and the MINIMUM taken. Dimensionless.
#
# THE SELECTION DOES NOT USE THE CONSTANT IT BOUNDS (R124). The first version
# picked one entry by its margin at `PATCH_TEST_EXACTNESS_COUNTER_DEFECT`, so the
# edge moved with the value it was supposed to bound: the named entry changed
# five times across a sweep and the published boundary was wrong by 2%.
#
# WHY IT EXISTS. `COUNTER_DEFECT` could be raised from `1e-6` to `1e+6` -- a
# defect multiplying one element by a million -- with the entire suite green.
# RAISING IT WEAKENS THE CLAIM: "the gate reddens on a sixth-digit slip" is
# strictly stronger than "the gate reddens on a 100x element". The
# `_COUNTER_DEFECT` form correctly exempts the value from the ceiling-below-
# counter ordering, since a defect size is not in the ceiling's quantity, and
# nothing replaced the guard that exemption removed.
#
# Reason for 6.0e7: measured, the smallest edge over the corpus and the ratio the
# shipped `1e-6` sits above it are `detection_edge`, `detection_edge_at` and
# `counter_defect_over_edge` in the generated figures -- typed here they were
# already wrong in the fourth digit when published (R176). The room this leaves
# is `counter_headroom_room`, generated beside them.
#
# THE MARGIN IS EATEN FROM ONE SIDE ONLY, and the sentence saying otherwise was
# re-introduced here after the plan had withdrawn it (R209). The selection is a
# MINIMUM over the corpus, so a minimum over a growing set is monotone
# non-increasing: a corpus round can only lower the edge and TIGHTEN this, never
# loosen it. A formulation change that improves sensitivity anywhere does the
# same. Both directions that exist point the same way, and the reviewer's corpus
# rounds have measured it: the room has fallen twice, `2.37x` to `2.19x` to
# `2.18x`, and has never risen. NO COUNT OF ROUNDS IS WRITTEN HERE (R213): "one
# direction, three times" stood in this entry and in the plan, the direction was
# right and the three counted nothing, and any such count goes stale the next
# time the reviewer adds an entry.
#
# AND THE SECOND FALL IS NOT ONE (BP0, CH5). `2.37x -> 2.19x -> 2.18x` was three
# laptop renders. The canonical machine gives `2.19x` for the same code, and the
# measured cross-machine spread for this figure is `1.005x` -- which is the
# whole of the `2.19 -> 2.18` step. The first fall is 8% and survives; the second
# is the size of the platform difference and is withdrawn as a trend. What the
# direction argument rests on is unchanged: both causes that exist tighten this,
# and the room has never risen. The published room is what absorbs that while
# still
# catching every order-of-magnitude raise, and the demonstration that it catches
# one is a shipped test.
#
# RE-DERIVED 2026-09-07 with the selection rule. The first value, `2.0e7`, was
# measured against the LARGEST edge under a selection that used the constant it
# bounds; against the smallest edge the ratio exceeds it and `2.0e7` fails.
#
# AND THE RATIO IS NOT RETYPED HERE EITHER (R194). This line read `2.537e+07`
# while `counter_defect_over_edge` and the test that prints it both read
# `2.534e+07` -- R176's species again, three lines below the sentence recording
# R176. Two more typed figures went with it in the paragraph above: a number
# that is generated is cited by name or it is not written.
# Set: 2026-09-07, F2. Retyped figures removed 2026-09-08, F2
PATCH_TEST_COUNTER_HEADROOM: Final[float] = 6.0e7

# CLASS: STRUCTURAL -- a convergence threshold, and it lives here because every
# decision constant does, `scripts/` included (R187). No counter-case, per AO2.
#
# The relative width at which the boundary bisection in `scripts/regen_figures.py`
# stops. A number that selects what gets published is a decision constant however
# small it looks, and `tests/test_no_tolerance_literals.py` does not scan
# `scripts/`.
#
# WHAT IT SELECTS is `boundary_margin_min_plateau` in the generated figures --
# how many bases share the published minimum to six figures. Its first Reason
# said the threshold moves `boundary_margin_min_at`, in the present tense, about
# a figure the same commit withdrew, and it carried no measurement at all: the
# value it justified had never been solved for (R196).
#
# Reason for 1e-6: MEASURED, one variable moved and everything else held over the
# shipped construction. The plateau is UNCHANGED from `1e-4` through `1e-12`, and
# coarsens above it -- three distinct and smaller values at `1e-3`, `1e-2` and
# `1e-1` -- so the figure converges between `1e-3` and `1e-4`, and `1e-6` carries
# two orders of margin. The published minimum itself is unchanged from `1e-2`
# down.
#
# THE SWEEP IS NOT TABULATED HERE, per BI3: its counts move with the corpus, and
# a table in this file is regenerated by nothing. It is in the step report, which
# is regenerated by rule, and what this entry needs from it is the convergence
# point above.
# Set: 2026-09-08, F2. Re-derived from a sweep 2026-09-08, F2
BOUNDARY_BISECTION_CONVERGENCE: Final[float] = 1e-6

# CLASS: ACCURACY -- carries DELTA_CALIBRATION_ULP_COUNTER below.
# G2.2 / V1.2 -- how far `injected_delta`'s measurement of the counter-defect may
# sit from the counter-defect's declared size, in UNITS OF `math.ulp` of that
# size. Dimensionless by construction.
#
# WHY IN ULP AND NOT RELATIVE (R156). This was `ROUNDOFF_IDENTITY` used as a
# relative band, and the record beside it said "one ULP". It is not: `1e-14`
# relative to `1e-6` admits `1e-20`, while one ULP of `1e-6` is `2.1176e-22` --
# a band of **47.22 ULP** described as one. The harm measured over 99 shipped,
# 372 grid and 360 random configurations is zero, and the record was wrong in
# three places, which is the finding.
#
# Reason for 4.0: the observed maximum deviation is 2 ULP, so the ceiling carries
# 2x of headroom. It is still 11.8x tighter than the `ROUNDOFF_IDENTITY` band it
# replaced. A value that must be raised is a formulation change, not a rounding
# one.
#
# THE DISTRIBUTION IS NOT TABULATED HERE (R184/BI3). A histogram stood in this
# comment and was one unseeded draw: re-drawn to the same protocol it gave a
# different table, and it contradicted the generated one in every cell. The
# distribution is `calibration_ulp_histogram` in docs/milestones/F2_figures.md,
# an EXACT count over every solved corpus entry -- no sampling, because
# resampling deterministic points measures the sampler (R185). What this entry
# needs from it is the maximum, and that is `calibration_ulp_worst`.
# Set: 2026-09-07, F2. Record corrected 2026-09-08, F2.
DELTA_CALIBRATION_ULP: Final[float] = 4.0

# COUNTER-CASE, INJECTED into the measured quantity (R163). The previous value,
# `40.0`, was compared with the ceiling directly -- `40 > 4` is arithmetic, and
# the test passed with the calibration's own assertion neutered. Nothing was
# being injected.
# Reason for 5.0: the smallest whole number of ULP above the ceiling `4.0`.
# Perturbing `injected_delta`'s result by this many ULP must fail the
# calibration, and it does. The reason is DEFINITIONAL -- it is where the next
# whole number above the ceiling falls -- and not extremal.
#
# THE MEASURED BOUNDARY, WHICH IS NOT 5 (R193). Injecting k ULP and running the
# shipped calibration: `+0`, `+1` and `+2` pass; `+2.5`, `+3`, `+4` and `+5`
# fail. The first whole number caught is 3, because the worst entry already sits
# 2 ULP from the declared size and the ceiling is 4. This entry and the test's
# docstring both read "so the counter sits at the first value that must be
# caught", which the same measurement they quoted refutes; R186 named both lines,
# and both were recorded closed while byte-identical, twice.
# Set: 2026-09-07, F2. Made an injection 2026-09-08, F2. Boundary corrected
# 2026-09-08, F2.
DELTA_CALIBRATION_ULP_COUNTER: Final[float] = 5.0

# CLASS: ACCURACY -- carries EXEMPT_RESPONSE_DRIFT_COUNTER below.
# G2.2 / V6.1 -- the relative move allowed in a recorded response of an
# exempt-but-detected (entry, defect) pair before the golden file is stale.
# Dimensionless; compared on the ratio to the ceiling, which is O(1).
#
# ITS OWN ENTRY AND, THIS TIME, ITS OWN NUMBER (R164). The first version gave it
# `1e-11` -- byte-identical to `SUBDIVISION_INVARIANCE`, the band it was declared
# to stop borrowing. Renaming a band is not giving a quantity its own tolerance,
# and it happened inside the commit that fixed borrowing, which is the finding.
#
# IN ULP, BECAUSE ITS OWN STATED REASON DEMANDS IT. "The admissible move is
# round-off in the ratio and nothing else" justifies a small multiple of an ULP,
# and `1e-11` relative is `4.81e+04` ULP of the smallest recorded ratio -- four
# orders looser than the reason it was given. Measured, the drift run-to-run and
# run-to-golden is `0.000e+00`: these responses are deterministic, same corpus,
# same code, same arithmetic.
#
# Reason for 4.0, BY THE CLASS THIS BELONGS TO (R174). The first attempt said
# "the same choice as `DELTA_CALIBRATION_ULP`, for the same argument -- four
# times a maximum observed at zero", which is not an argument: four times zero is
# zero, and the reasoning it cited had been withdrawn forty lines above in the
# same diff.
#
# What the two constants share is their CLASS: both floor a floating-point ratio
# whose exact value is a rounding of the same expression, and the basis for that
# class is `DELTA_CALIBRATION_ULP`'s observed maximum, `calibration_ulp_worst` in
# docs/milestones/F2_figures.md. That distribution is an EXACT count over every
# solved corpus entry -- nothing is drawn and nothing is seeded, and this pointer
# still said "seeded histogram" a round after the seeding was removed (R195).
# `4.0` is twice that maximum -- room for a platform whose last bit
# rounds differently, and nothing wider. This quantity's own measured drift is
# `0.000e+00`, which is why it takes the class's number rather than one of its
# own: there is nothing here to fit to.
# Set: 2026-09-07, F2. Re-derived in ULP 2026-09-08, F2.
EXEMPT_RESPONSE_DRIFT_ULP: Final[float] = 4.0

# COUNTER-CASE, injected into a recorded value.
# Reason for 10.0: the smallest round multiple above the ceiling that leaves the
# injection unambiguous. The shipped test perturbs a golden ratio by this many
# ULP and requires the comparison to fail.
# Set: 2026-09-07, F2. Re-derived in ULP 2026-09-08, F2.
EXEMPT_RESPONSE_DRIFT_ULP_COUNTER: Final[float] = 10.0


# CLASS: ACCURACY -- carries SOLVE_BACKWARD_ERROR_FACTOR_COUNTER_DEFECT below.
# Rung 1 -- the solve's BACKWARD ERROR, in multiples of eps:
#
#     ||K u - f|| / (||K||_max ||u||_2 + ||f||_2)  <=  FACTOR * eps
#
# Dimensionless. This is how large a perturbation of the system the computed
# solution solves exactly, and for a backward-stable factorisation it is a small
# multiple of eps whatever the scaling of the problem.
#
# WHY NOT ||r|| / ||f||, WHICH THIS REPLACES (R45). That normalisation was gated
# at 1e-13 and restricted to metres on the recorded ground that "the residual is
# conditioning-limited, and cond(K_ff) is a property of the unit system". THE
# CELL REFUTES IT. cond(K_ff) is a property of the MATRIX, so it is identical for
# all six states at a scale; holding it fixed and varying the state:
#
#   state          S=1e-3 r/f    bwd      K.u/f        S=1 r/f     bwd
#   axial            3.54e-16  6.17e-17  4.7e+00      5.93e-16  1.03e-16
#   curvature        1.93e-15  1.54e-19  1.3e+04      1.06e-15  3.09e-17
#   twist            2.30e-13  1.62e-21  1.4e+08      1.47e-15  1.02e-17
#   shear            2.49e-15  2.20e-19  1.1e+04      1.73e-15  4.73e-17
#   curvature_xz     2.12e-15  1.69e-19  1.3e+04      7.47e-16  2.18e-17
#   shear_xz         1.96e-15  1.73e-19  1.1e+04      1.14e-15  3.11e-17
#
# Five of six states at S = 1e-3 sit at round-off at the very conditioning that
# was blamed. The whole excursion is the `twist` cell, whose ||K||.||u||/||f|| is
# 1.4e+08 against 4.7 for axial -- a collapsing LOAD norm, not conditioning.
#
# Reason for the value: the worst backward error over all eighteen cells the gate
# runs is 1.0343e-16, which is 0.47 eps. 8.0 sits 17x above it, and the whole
# spread across the eighteen is 1.62e-21 .. 1.03e-16 -- so the ceiling is bounded
# by the arithmetic rather than by any property of the load case, which is the
# point of the change. It is asserted at ALL THREE unit scales, where the
# quantity it replaces could only be asserted at one.
# Set: 2026-09-04, F2
SOLVE_BACKWARD_ERROR_FACTOR: Final[float] = 8.0

# COUNTER-CASE, a DEFECT SIZE (BG1): the relative error in the solved field that
# must still push the backward error above the ceiling. Measured by bisection on
# the shipped predicate, per cell -- and it is strongly configuration-dependent,
# which is the cost of this normalisation and is recorded rather than buried:
#
#   worst cell   twist  at S = 1e-3   detects a solution wrong by 2.5283e-07
#   best  cell   axial  at S = 1      detects a solution wrong by 1.0103e-14
#
# A spread of 2.5e7 across the eighteen cells the gate runs -- which is the whole
# of the trade this normalisation makes, and the first version of this comment
# wrote "see below" where those two numbers belong and then never gave them.
#
# The counter, 1.0e-6, is set above the WORST cell (2.53e-07) so every cell
# catches it. NOTE the trade this makes explicit: ||r||/||f|| detected a wrong
# solve at ~1e-12 everywhere, and this detects one at 1.0e-14 in the best cell
# and 2.5e-07 in the worst. Backward error is the right measure of
# STABILITY and a weaker detector of a WRONG ANSWER on a badly scaled system;
# both are now reported by `SolveResult` and only this one is gated.
# Set: 2026-09-04, F2
SOLVE_BACKWARD_ERROR_FACTOR_COUNTER_DEFECT: Final[float] = 1.0e-6


# CLASS: ACCURACY -- carries RESULTANT_EXACTNESS_COUNTER below.
# G2.2 / V1.2 -- deviation of the RECOVERED element end forces from the analytic
# resultants of the constant-strain state: EA*eps, EI*kappa in each bending plane,
# GJ*phi', and for state 4 the constant shear P with its linear moment P(L-x).
# Relative, scaled per element by the largest analytic resultant of that element,
# so it is dimensionless.
#
# A SEPARATE ENTRY FROM PATCH_TEST_EXACTNESS BECAUSE IT IS A DIFFERENT QUANTITY.
# The displacement check compares a field; this compares a stiffness-weighted
# FIRST DIFFERENCE of that field, so it loses two to three digits to cancellation
# and cannot share a ceiling. Reusing the displacement ceiling for a quantity of
# another kind is what made the solve-residual line it replaces unfalsifiable
# (R41) -- that line sat at 1e-15 against a 1e-12 ceiling and did not move under a
# defect that failed the displacement check by eleven orders.
#
# Reason: exact in exact arithmetic -- the states are reproduced exactly, so the
# recovered forces are the analytic ones. Measured worst over six states x two
# orientations, on the shipped path:
#
#   S = 1e-3   axis-aligned 2.892e-11   skew 4.558e-11   <- worst
#   S = 1      axis-aligned 1.525e-13   skew 3.921e-13
#   S = 1e+3   axis-aligned 2.900e-13   skew 1.484e-12
#
# 1e-9 sits 22x above the worst of those and ~700x below the counter-case.
#
# OPERATING POINT, because a ratio against a varying denominator carries one or it
# carries nothing (ninth guard). These are the scales the shipped test runs
# (S = 1e-3, 1, 1e3) at the posed geometry, tube 0.6/0.012, element lengths
# 0.79..3.27 m. The error tracks the conditioning of the solve rather than the
# element: outside that band it grows to 7.2e-10 at S = 1e-4, where
# cond(K_ff) = 6.0e10. The ceiling is claimed over the band the test runs, not
# beyond it.
# Set: 2026-09-04, F2
RESULTANT_EXACTNESS: Final[float] = 1e-9

# COUNTER-CASE, measured on the same quantity and in the WORST state.
# A 1e-6 relative stiffness error in ONE interior element moves the recovered
# resultants by 6.898e-07 (axial, twist), 6.934e-07 (both curvature states) and
# 7.983e-07 (both shear states). The counter is set just below the SMALLEST, so
# every state must catch a one-part-in-10^6 stiffness error through the forces as
# well as through the displacements.
#
# WHAT THIS CHANNEL IS FOR, corrected (R47). An earlier version of this entry
# said the resultant channel is "~6.4x the more sensitive", from the ratio of raw
# responses to one 1e-6 defect (6.90e-07 against 1.08e-07). That is a RESPONSE
# ratio standing where a DECISION ratio is meant, and the two channels are
# compared against ceilings a thousand times apart. Inverting each shipped
# predicate instead -- the smallest single-element stiffness defect each one
# actually detects:
#
# THE TABLE IS NOT HERE (R92/BI3), and the "~150x weaker" it used to carry is
# WITHDRAWN with it. Both were measured against the field channel's RETIRED
# quantity. On the predicates that ship, the ratio spans 5.1x (twist) to 14303x
# (axial) -- three orders, where a single number stood. The regenerated table is
# in `tests/verification/rung1/test_patch_test.py` beside
# `RESULTANT_DETECTION_THRESHOLD`, which is the code that consumes it, and in
# docs/reports/F2/step-4.md revision 10.
#
# What the spread says is the argument this entry needs and the single number
# never made: the two channels are sensitive to DIFFERENT things, so both are
# kept. This one is a different quantity, checked against statics rather than
# against the solve, catching four of five planted sign defects in its own
# analytic table. NOTE against that claim (R53): with I_y == I_z forced by every
# shape `basis.kappa` knows, it cannot see an I_y/I_z swap either.
# Set: 2026-09-04, F2
RESULTANT_EXACTNESS_COUNTER: Final[float] = 6.8e-7


# CLASS: ACCURACY -- carries MATRIX_SYMMETRY_COUNTER below.
# G2.1 / V1.1 -- symmetry of an assembled or element stiffness matrix, relative,
# scaled by the largest entry. Dimensionless.
#
# Reason: K is symmetric in exact arithmetic (Maxwell-Betti), so the only
# admissible asymmetry is accumulation through the 12x12 triple product and the
# scatter-add. Measured on the element and on a 5-member assembly: max |K - K^T|
# / max |K| is 0.0 exactly for a single element and 2.4e-16 assembled. 1e-9 sits
# ~7 orders above that, which covers longer chains without admitting a
# transposed block (which shows at O(1)).
# Set: 2026-09-03, F2
MATRIX_SYMMETRY: Final[float] = 1e-9

# COUNTER-CASE: a MIS-INDEXED SCATTER -- the element's columns landing on the
# wrong node's DOF while its rows land correctly. Measured on a 5-member frame:
# max |K - K^T| / max |K| = 7.902e-02, eight times the ceiling.
#
# CORRECTED BY INJECTING IT (BG1). This entry said the defect was "one transposed
# element block ... 3.1e-01". An element contribution is SYMMETRIC
# (max|kg - kg^T| / max|kg| = 3.7e-17), so transposing one is a no-op: the
# assembly's asymmetry stays at 3.711e-17, which is its clean value. The named
# defect was not a defect, and nothing ran it for four rounds. Measured
# alternatives, on the same frame:
#
#   transpose the block (the named defect)   3.7107e-17   <- no-op, = clean
#   columns scattered to the wrong node      7.9020e-02   <- the counter
#   upper triangle only                      5.0000e-01
#   one off-diagonal entry, 5%               2.5000e-02
#
# The value 1e-2 stands on the second and third rows. Only the sentence moved.
# Set: 2026-09-03, F2; basis corrected 2026-09-04
MATRIX_SYMMETRY_COUNTER: Final[float] = 1.0e-2


# CLASS: ACCURACY -- carries ROUNDOFF_IDENTITY_COUNTER below.
# Rung 1 -- relative agreement for a property that is EXACT in exact arithmetic
# and is asserted at round-off: triad orthonormality, reciprocity of a
# flexibility matrix, the equality of two algebraically identical expressions.
# Dimensionless in every use.
#
# Reason: these have no discretisation error to bound, only floating-point
# accumulation. Worst measured across its nine sites is 2.2204e-16 -- one ULP.
# 1e-14 sits ~45x above that.
#
# SET BY THE TIGHTEST MEMBER OF THE GROUP (BD1). It was briefly 1e-12, which was
# a 100x WIDENING of three sites that had carried 1e-14 and measured 3.7e-17 ..
# 1.9e-16 -- 53x to 267x of headroom, and nothing forcing the change. That was
# done while the commit message asserted no value had been loosened. When a group
# of literals is consolidated the new entry takes the tightest member, or the
# group splits; it never takes a round number chosen for looking tidy.
# Set: 2026-09-03, F2
ROUNDOFF_IDENTITY: Final[float] = 1e-14

# COUNTER-CASE: the smallest defect these assertions must still catch. A single
# sign error or a swapped index in any of the quantities involved is O(1); the
# subtlest real case is the non-orthogonal I + [theta x] first-order map, whose
# orthonormality deviation is O(theta^2) because the map is orthogonal to first
# order: ``M^T M - I = K^T K``. Measured:
#
#   theta      ||M^T M - I||_max     theta^2
#   1e-08          5.7022e-17         1.0e-16
#   1e-06          1.5019e-12         1.0e-12
#   1e-04          1.5018e-08         1.0e-08     <- the counter
#   1e-02          1.5018e-04         1.0e-04
#
# CORRECTED BY INJECTING IT (BG1). This entry said the 1e-08 deviation came from
# "theta = 1e-8", which is wrong by EIGHT ORDERS -- at that angle the deviation is
# 5.7e-17, i.e. round-off. The value stands; the angle that produces it is 1e-4.
# Set: 2026-09-03, F2; basis corrected 2026-09-04
ROUNDOFF_IDENTITY_COUNTER: Final[float] = 1.0e-8


# CLASS: ACCURACY -- carries DETECTION_THRESHOLD_BAND_COUNTER below.
# G2.2 / V1.2 -- how closely a perturbation AT a recorded detection threshold must
# reproduce the ceiling. Relative, dimensionless.
#
# Reason: the thresholds are computed as TOL/sensitivity, so perturbing by one
# should land the error on TOL exactly; the deviation is the departure from
# linearity over that range. Worst measured across the six states: 9.9523e-03.
# 0.05 sits 5x above it -- enough that linearity's own curvature does not trip the
# check, tight enough that a real change in sensitivity does.
#
# DECLARED LATE. This was R13's THIRD bare literal, and the regex scanner it was
# reported against read the line as clean because a tolerance NAME appeared
# elsewhere on it (`pytest.approx(PATCH_TEST_EXACTNESS, rel=0.05)`). The AST
# scanner checks the argument node, so the hole is closed by construction.
# Set: 2026-09-03, F2
DETECTION_THRESHOLD_BAND: Final[float] = 0.05


# COUNTER-CASE: a sensitivity change large enough to matter. If a formulation
# change moved any state's sensitivity by 25%, perturbing by the recorded
# threshold would miss the ceiling by that much and this must catch it.
# Set: 2026-09-03, F2
DETECTION_THRESHOLD_BAND_COUNTER: Final[float] = 0.25


# ---------------------------------------------------------------------------
# Rung 2 -- The element is the element it claims to be
# Cantilever slender/stubby (G2.3/V2.1-2.2), torsion (V2.3), 3D coupling (V2.4),
# free-free frequencies (G2.4/V2.5), releases and rigid links (V2.6).
# Compared against closed-form textbook solutions.
# ---------------------------------------------------------------------------

# (no entries yet -- F2)


# ---------------------------------------------------------------------------
# Rung 3 -- The model is the platform
# Mass correctness (G3.1a/V3.1a), mass consistency (G3.1b/V3.1b), YAML
# round-trip (G3.2/V3.2), exact section properties (G3.3/V3.3).
#
# Note G3.1b is the convergence criterion of a design loop, not a code gate --
# see PLAN.md sec.6 F3. Its tolerance expresses "close enough that the analysed
# loads are representative", which is a different kind of claim from every other
# entry in this file and must say so in its comment.
# ---------------------------------------------------------------------------

# (no entries yet -- F3)


# ---------------------------------------------------------------------------
# Rung 4 -- The loads are the loads
# Equilibrium residual (G4.1/V4.1), rigid-body acceleration (G4.2/V4.2),
# hydrostatic (G4.3/V4.3), mapping conservation (G4.4), residual convergence
# rate (G4.5), hydrostatic reconciliation (G4.6), frame round-trip (V4.4),
# strip integration (V4.5), reconstruction integrity (G1.6).
#
# G4.1's tolerance must NOT be set above the timestamp-alignment floor. The
# exporter aligns each force to the index of the state it was evaluated from,
# which removes an O(omega*dt) ~ 3.2% residual at full scale; declaring that
# floor instead would put the tolerance at precisely the level that hides a real
# load-path defect. G4.5 guards the alignment by convergence RATE, not by
# magnitude. See docs/milestones/F1.md sec.6 and PLAN.md sec.8.
# ---------------------------------------------------------------------------

# (no entries yet -- F1/F4)


# CLASS: ACCURACY -- carries INTERCHANGE_CHANNEL_DRIFT_ULP_COUNTER below.
# G1.1 / V2 -- a channel of a writer-produced record, compared with the closed
# form the generator used. In ULP OF THE CHANNEL'S OWN AMPLITUDE, which is Q8's
# second local class in the plan's own words, and is what makes one number
# cover channels whose values span two orders: `rotation` at 2.5e-02 and
# `acceleration` at 3.0e+00 are the same distance apart in ULP and four orders
# apart in absolute difference.
#
# WHY A BAND AT ALL, when the assertion it replaces was bit-exactness. `sin`
# and `cos` are not correctly rounded and the standard does not require them to
# be: no two libm implementations are obliged to agree in the last bit. The
# fixture is a committed golden produced on one machine, so bit-exactness
# asserted a property the arithmetic does not have -- thirteen of the pairs
# failed on CI for eleven rounds and every one of them was the last bit.
#
# THE ARITHMETIC CHANNEL IS STILL EXACT AND IS NOT IN THIS BAND. `time/t` is
# `arange(N+1) * DT`, no transcendental anywhere, and it agrees bit for bit on
# both machines -- 25 of 25 values. A band that covered it would be a band
# fitted to the loosest channel.
#
# Reason for 2.0: TWICE A MEASURED WORST, and it is worth saying which
# measurement. Q8 fixed this class at `<= 2` ULP on the basis of thirteen
# CI-versus-local pairs, every one of them `0.5` or `1.0` ULP of its channel's
# amplitude -- so the number is derived from the disagreements it now admits,
# which is legitimate at twice the worst and is stated that way rather than as
# a number that predated its evidence (R325).
#
# This entry adds an INDEPENDENT re-measurement of the same quantity: on the
# canonical machine the worst over all thirteen pairs is `1.0` ULP and most are
# `0.5`; on the machine the fixture was produced on it is `0.0`, every value
# exact; and every determinism leg of run 34545832426 reports the same `1.0`,
# across three CPU models. Twice the worst is the rule
# `EXEMPT_RESPONSE_DRIFT_ULP` was set by.
# The per-channel table is in the step report, regenerated by
# `scripts/measure_channel_drift.py`, and is not retyped here (BI3).
# Set: 2026-09-10, F2
INTERCHANGE_CHANNEL_DRIFT_ULP: Final[float] = 2.0

# COUNTER-CASE, injected into one value of one channel and run through the
# shipped comparison.
# Reason for 3.0: one ULP past the band, which is the smallest injection that
# is unambiguously outside it. A counter at 2.0 would test the comparison
# operator; a counter an order out would pass a band ten times too wide.
#
# INJECTED BEYOND THE CLEAN DEVIATION AT THE SITE, NOT BEYOND THE REFERENCE
# (R324). Added to the reference, a 3 ULP injection at a site the canonical
# machine already holds 1 ULP low measures 2 against a band of 2, and the
# counter then fails on the machine the band was measured on -- the margin was
# decided by which way a libm's last bit fell. Measured from the site and added
# beyond it, the delta that reaches the comparison is 3 ULP on every machine
# and the margin is AT LEAST one ULP by construction -- it is |clean| + 1,
# and one is its floor (R340). The operating point is recorded
# with it: the clean deviation is 0.0 ULP at that site here and up to 1.0 ULP
# on the canonical machine.
# Set: 2026-09-10, F2
INTERCHANGE_CHANNEL_DRIFT_ULP_COUNTER: Final[float] = 3.0


# ---------------------------------------------------------------------------
# Canonical files -- cross-platform agreement (Q8, third class)
#
# Q8 makes CI canonical for the goldens, for every platform-dependent tolerance
# and for `docs/milestones/F2_figures.md`. These two govern what a NON-canonical
# machine asserts about a canonical file. They are not physics and they do not
# enter a solve; they bound the disagreement between two renders of the same
# code on two machines.
# ---------------------------------------------------------------------------

# CLASS: ACCURACY -- carries FIGURE_FLOOR_CLASS_SPREAD_COUNTER_DEFECT below.
# It bounds agreement between two machines rather than agreement with a
# reference solution, which is why `PLATFORM` reads better -- and the class
# vocabulary is ACCURACY or STRUCTURAL, checked at rung 3, and the rule that
# matters attaches to ACCURACY: it carries a counter. Inventing a third
# class name to describe the same obligation would be a gate edit made to
# suit a label.
# A dimensionless FACTOR between two renders of the same figure: max/min, so
# 1.0 is agreement and the value is invariant under the figure's units and
# under which machine is called canonical.
#
# WHICH FIGURES IT APPLIES TO. Q8's third local class: figures whose value is
# itself a round-off magnitude -- an out-of-balance of a field that is exact in
# exact arithmetic, or a ratio of two near-zero eigenvalues. The numerator is
# round-off, and two BLAS kernels differ in their last bits by O(1) factors.
# The other two classes -- exact for arithmetic-only, 2 ULP through a
# transcendental -- were written for physical channels and do not reach these.
#
# Reason for 1.5: the measured spread between the canonical CI render and a
# laptop render of the same commit, over the rows that move at all. THE COUNT
# IS RE-TAKEN AT EVERY COMMIT THAT MOVES IT AND IS NOT WRITTEN HERE (R316):
# `forty-seven` was the old file's LINE count and `thirty-eight` was a row
# count of a superseded render, and both were published as the basis of this
# number. The count, the denominator and the per-row table are in the step
# report, regenerated by rule; what this entry needs is the largest, and the
# largest is `rigid_body_mode_ratio` at 1.336x; the rest are 1.078x
# and below. The table is in docs/milestones/F2.md, Q8, and is not retyped here
# (BI3/R194).
#
# WHAT MAKES 1.5 THE RIGHT SIDE OF THE MEASUREMENT rather than a round number
# above it: the smallest margin any floor-class figure has to its own ceiling is
# `counter_headroom_room` at 2.19x. 1.336 < 1.5 < 2.19, so a spread inside this
# bound cannot carry a decision across a ceiling, and a spread outside it is a
# finding before it is a rounding difference. Both inequalities are asserted by
# `tests/test_figure_local_check.py`, so the gap closing is a red build rather
# than a comment nobody re-reads.
# Set: 2026-09-10, F2
FIGURE_FLOOR_CLASS_SPREAD: Final[float] = 1.5

# COUNTER-CASE, INJECTED as a figure moved between the committed render and the
# local one, run through the shipped `--check`.
# Reason for 1.6: the smallest spread above the ceiling that is not on it. A
# counter sitting exactly at 1.5 tests the comparison operator; this tests the
# gate. It is 1.2x the largest spread ever measured.
# Set: 2026-09-10, F2
FIGURE_FLOOR_CLASS_SPREAD_COUNTER_DEFECT: Final[float] = 1.6

# CLASS: ACCURACY -- carries FIGURE_ARGMIN_TIE_WINDOW_COUNTER_DEFECT below.
# A dimensionless FACTOR on an extremum over the corpus: an entry is named in a
# figure's tie set when its own value is within this factor of the extremum.
#
# WHY A SET AND NOT A WINNER. `detection_edge_at` is a NAME, not a number, and
# the winner flips between two entries on two machines. No tolerance on a value
# can express which name is admissible, and dropping the name destroys the
# location of an extremum -- which the recorded rule "a residual destroys
# information; report sign and location alongside a norm" forbids. So the
# render names every entry inside the window, sorted, and a flip inside the set
# changes no byte.
#
# Reason for 1.01: the two entries that swap are 1.0041x apart
# (`ci_plateau_D0p0689_roll1p017_aniso9p6e5` and
# `ch_edgemin_D0p0758_roll1p05_aniso9p4e5`), and the next entry up is 1.0216x.
# The window sits above the measured flip and below the next candidate, with
# room on both sides -- it is bracketed by measurements rather than chosen.
# At 1.5x the set would be sixteen entries and the figure would say nothing.
# Set: 2026-09-10, F2
FIGURE_ARGMIN_TIE_WINDOW: Final[float] = 1.01

# COUNTER-CASE: an entry at the next candidate's distance must NOT be named.
# Reason for 1.0216: the measured position of the third entry, which is the
# first one the window has to exclude. A counter further out would pass a
# window twice this size.
# Set: 2026-09-10, F2
FIGURE_ARGMIN_TIE_WINDOW_COUNTER_DEFECT: Final[float] = 1.0216


# ---------------------------------------------------------------------------
# Rung 5 -- Independent confirmation
# CalculiX global cross-check (G7.1/V5.1), stress recovery (G6.2/V5.2), code
# check hand calculations (G6.1/V5.3).
#
# G7.1's values are stated in PLAN.md sec.6 F7 (0.5% displacement, 1% member
# force). An exceedance is explained in writing before the milestone closes --
# never absorbed here.
# ---------------------------------------------------------------------------

# (no entries yet -- F6/F7)


# ---------------------------------------------------------------------------
# Rung 6 -- It stays fixed
# Golden-file regression (V6.1). A golden-file change requires a written
# explanation of why the numbers moved, in the milestone closure artifact.
# ---------------------------------------------------------------------------

# (no entries yet -- F6)
