"""The single home for every numerical tolerance in FloatFEA.

**This file is deliberately empty of values.** It exists before the first
tolerance does, because a guardrail that arrives after the thing it guards
never takes: by then tolerances have already been scattered into call sites and
default arguments, and consolidating them becomes a refactor nobody schedules.

---

## The rule

Every numerical tolerance in this repository lives here. No exceptions, no
local literals, no default arguments carrying a tolerance. This includes
anything that functions as a tolerance under another name -- convergence
thresholds, comparison epsilons, "small number" guards, tier cutoffs in
screening, and any factor introduced to make two numbers agree.

Do not modify this file to make a failing test pass. If a test fails, the
default hypothesis is that the code is wrong, not that the tolerance is tight.

Changing a value requires a written justification in the milestone closure
artifact (`docs/closure/F<n>.md`) naming the physical or numerical reason the
previous value was incorrect. A tolerance change in the same commit as the code
change it rescues will be rejected in review.

See `CLAUDE.md` sec. Tolerances and `WORKFLOW.md` sec. "The one habit that
matters most".

---

## Two classes, and the counter-case rule binds on only one (AO2)

Every entry is **STRUCTURAL** or **ACCURACY**, and the distinction is declared in
its comment because a rule applied where it does not fit gets weakened to
accommodate.

**STRUCTURAL** — a threshold on a physical or numerical *condition*, which fires
by design when the condition holds. `MEMBER_ORIENTATION_DEGENERACY` fires on the
platform's vertical spars on purpose; it exists to force an explicit choice, not
to be tuned until it stops firing. Demanding a "smallest defect it must still
catch" of such an entry would force an artificial number.

**ACCURACY** — a ceiling on a residual or error that is *supposed* to be small.
These are the ones "the test fails, widen the tolerance" can reach, and they carry
a **paired counter-case**:

    X          = <ceiling the check asserts>
    X_COUNTER  = <smallest defect that must still fail>

A counter comes in two kinds and they are not interchangeable (BG1):

* `X_COUNTER` is a **response magnitude**, in the assertion's own quantity, and
  it must sit above the ceiling -- so widening `X` toward it eventually breaks a
  test.
* `X_COUNTER_DEFECT` is a **defect size**: the perturbation that must still be
  caught. It is used where the ceiling is not a constant, so no ordering between
  the two numbers exists to check. It carries a stronger obligation instead:
  a test injects it and asserts the shipped assertion FIRES.

The second kind exists because the first can be inert. `RESULTANT_EXACTNESS`
could be widened 680x in silence, because its only guard was `ceiling < counter`
-- a comparison between two literals in this file, with nothing running the
defect. **A counter that nothing injects is a number, not a check.**

**And nothing else.** An `X_MEASURED` -- the worst value seen at the entry's
sites -- lived here briefly (BD1) and was removed (BE2). A hand-written literal
in this file, compared against two other hand-written literals in this file, is
a check whose subject the check itself supplies: four of the nine were wrong on
arrival, two of them measured on a solve path that had been deleted one commit
earlier, and no test could tell. **Measured values belong in the step report,
generated by the run at the report's own commit.** What lives here is the
ceiling, the counter-case, and where the justification is written down.

The pairing is what makes the ceiling an execution result rather than a
reviewer's judgement:

* **existence is mechanically checkable** — every `X` has an `X_COUNTER`;
* **it cannot be satisfied by prose**, because `X_COUNTER` is a number an
  executable test consumes;
* **widening `X` toward `X_COUNTER` eventually breaks the counter-test.**

That last property is the point. A tolerance with a floor but no ceiling can
always be widened one more order and still look principled.


## The comment convention

Every entry carries four things, and a reviewer should be able to check the
value without reading any other file:

1. the **gate** it serves (G2.1, G4.1, ...) and the verification case (V1.1,
   V4.5, ...) from `docs/verification/README.md`;
2. **what is being compared** -- absolute or relative, and to what reference;
3. the **physical or numerical reason** the value is what it is, not merely that
   it passes;
4. the **date and milestone** it was last changed under.

Template::

    # G<n.n> / V<n.n> -- <what is compared, absolute or relative>
    # Reason: <physical or numerical basis for this magnitude>
    # Set: <YYYY-MM-DD>, <milestone>
    NAME: Final[float] = <value>

A value whose comment says only "empirically determined" or "matches the
reference" is not documented; it is a fudge factor with better manners.

---

## Layout

Entries are grouped by verification-ladder rung, so that a reviewer reading a
red test at rung 1 sees rung 1's tolerances together and is not invited to
compare them against rung 5's, which answer a different kind of question.

Rungs are defined in `docs/verification/README.md`.
"""

from __future__ import annotations

from typing import Final

# ---------------------------------------------------------------------------
# Model construction -- geometric degeneracy guards
#
# Not tied to a verification rung: these guard the construction of the model
# itself, and they fail loudly at build time rather than producing a wrong
# number at solve time.
# ---------------------------------------------------------------------------

# CLASS: STRUCTURAL -- fires by design on vertical members; no counter-case.
# G0.2 / docs/conventions.md sec. "Member local axes" -- minimum |z_hat x x_hat|
# for the DEFAULT global-Z orientation reference to be admissible on a member.
# Dimensionless; equals the sine of the member's angle from vertical.
#
# Compared: the magnitude of the cross product used to build local y, against
# this floor. Below it the model builder RAISES and demands an explicit
# orientation node or roll angle. It does not fall back to another axis.
#
# Reason: local y is built from z_hat x x_hat, so its direction error amplifies
# any perturbation in the member axis by 1/|z_hat x x_hat|. The construction is
# exactly singular at vertical and ill-conditioned near it. 0.05 corresponds to
# 2.87 deg from vertical and bounds that amplification at 20x. The spars in this
# platform are vertical, so this guard fires on the real model by design -- it
# exists to force an explicit choice, not to be tuned until it stops firing.
# Raising it excludes valid members; lowering it admits members whose section
# axes are not reliably oriented.
# Set: 2026-08-10, F0
MEMBER_ORIENTATION_DEGENERACY: Final[float] = 0.05


# CLASS: STRUCTURAL -- a modelling admission limit. It fires by design on parts
# that are not beams, and it exists to force an explicit choice (an F7 shell
# sub-model), not to be tuned until it stops firing. No counter-case, per AO2.
#
# BH0 / docs/conventions.md sec. "Beam admission limit" -- the smallest member
# length-to-depth ratio for which a Timoshenko beam element is an admissible
# model. Dimensionless: member length over `D = 4 sqrt(I/A)`.
#
# ON THE MEMBER, NOT THE ELEMENT, and that was measured rather than assumed. The
# gate's own mesh has a member at L/D = 16.12 and two of its five elements at
# L/D = 1.32 and 1.50, so an element-wise limit of 2 would reject the patch
# test's own model. Beam validity is a property of the physical member;
# subdividing it is ordinary practice and changes nothing.
#
# Reason for 2.0: shear-flexible beam kinematics still assume plane sections and
# a length over which stresses redistribute, and below L/D ~ 2 there is no such
# length. The value is a MODELLING JUDGEMENT, proposed by the supervisor and
# PENDING XABIER'S CONFIRMATION -- it is not derived from a measurement here, and
# it is written down as a judgement rather than dressed as one.
#
# WHAT IT COSTS AND WHAT IT BUYS, measured. Sweeping member L/D with the gate's
# own station ratios, the weakest state's response to a 1e-6 single-element
# stiffness defect (against PATCH_TEST_EXACTNESS_COUNTER = 1.0e-7):
#
#   L/D    0.50    1.00    1.50 | 2.00    3.00    8.00   16.10   48.00
#   resp  9.50e-8 8.80e-8 1.08e-7| 1.08e-7 1.07e-7 1.07e-7 1.08e-7 1.08e-7
#          FAILS   FAILS        | -------- admitted range --------
#
# Below the limit the gate's own negative control FAILS -- the counter-case is
# not detected at L/D = 0.5 or 1.0. That is the concrete cost of analysing a
# non-beam as a beam, and it is the measurement the limit rests on. Over the
# admitted range the response is flat to 0.9% and scale-free in D: at L/D = 2 it
# is 1.0805e-07 for every diameter from 0.1 m to 4 m.
# Set: 2026-09-04, F2
BEAM_ADMISSION_L_OVER_D: Final[float] = 2.0


# CLASS: STRUCTURAL -- a condition (is this DOF alive?), not an error ceiling.
# G1.6 / diagnostics -- floor below which a DOF carries no signal and MUST NOT
# enter any aggregate statistic. Relative, against the largest reference
# magnitude across the DOF being aggregated.
#
# Compared: each DOF's reference magnitude (|mu|, |B|, whatever the statistic is
# formed over) divided by the maximum over that same set, against this floor.
# Below it the DOF is structurally dead and `frames.live_dof` excludes it.
#
# Reason: a body of revolution has no yaw radiation, so yaw `mu` on this platform
# is 1.2e-17 against 4.2e-01 in surge -- a ratio of 3e-17, which is round-off, not
# a small physical quantity. Including such a DOF in a correlation or a norm
# computes a statistic over noise and reports it as a measurement; it did exactly
# that once, moving an AG5 correlation from +0.53 to +0.65. The floor sits at
# 1e-12 because double precision gives ~1e-16 relative and four orders of headroom
# separates "accumulated round-off" from "small but real": the smallest genuinely
# physical ratio measured on this platform is heave's 0.01x, twelve orders above.
# Raising it would begin discarding real DOF; lowering it re-admits round-off.
# Set: 2026-08-26, F1
DEAD_DOF_RELATIVE_FLOOR: Final[float] = 1e-12


# CLASS: STRUCTURAL -- a condition (is this reference admissible here?).
# G1.6 / diagnostics -- tolerance at or below which an INTERPOLATED reference is
# inadmissible and `frames.assert_reference_supports` refuses the comparison.
# Relative, same units as the comparison tolerance it is checked against.
#
# Compared: the tolerance a comparison intends to assert at, against this floor.
# At or below it the reference must come from a solved/exact point, not from
# interpolation between grid points.
#
# Reason: interpolating a reference across a grid gap injects an error set by how
# much the quantity varies over that gap, and it is invisible in the result. The
# measured case: omega = 2.000377 sits at 48.6% of the gap 1.930166 -> 2.074677 --
# dead centre, because case frequencies are chosen for physics, not grid alignment
# -- and B varies ~60% across it. That produced a residual of 5.914e-04 against a
# true reconstruction error of 1.359e-15: ELEVEN orders, entirely from the
# interpolation. 1e-3 sits just above the measured 5.9e-4 artifact, so a
# comparison asserting at or below it cannot distinguish its own interpolation
# from the thing it is measuring. Raising it would admit interpolated references
# into comparisons the artifact dominates; lowering it below ~6e-4 would admit the
# exact case already measured to fail.
# Set: 2026-08-27, F1
INTERPOLATED_REFERENCE_TOLERANCE_FLOOR: Final[float] = 1e-3


# CLASS: ACCURACY -- carries PANEL_RECONSTRUCTION_RESIDUAL_COUNTER below.
# G1.6 / V4.6 -- ceiling on the panel-reconstruction residual
# ||R - T||_F / ||T||_F, where R integrates the exported per-panel radiation
# pressure over each body's panels and T is w^2*A + i*w*B from the same BEM solve.
# Relative, Frobenius, dimensionless.
#
# Reason: the identity is EXACT in exact arithmetic -- both sides are the same
# surface integral, one evaluated panel-wise and one by the solver -- so the only
# admissible residual is floating-point accumulation. Measured 1.308e-15 on the
# 12-buoy platform (10,560 panels, 72 DOF) and 1.518e-16 on the committed
# 64-panel fixture. 1e-12 sits ~3 orders above the larger of those, which covers
# BLAS/platform variation in the einsum reduction without admitting anything
# physical: the smallest deliberate defect measured -- ONE panel of 10,560 with
# its area perturbed by 1% -- produced 1.082e-05, seven orders ABOVE this ceiling.
# Raising it toward 1e-5 would begin admitting real geometry errors; lowering it
# to ~1e-15 would make the gate sensitive to summation order.
# Set: 2026-08-28, F1
PANEL_RECONSTRUCTION_RESIDUAL: Final[float] = 1e-12

# COUNTER-CASE for the above -- the smallest defect the gate must still fail.
# Measured, not chosen: ONE panel of the 10,560-panel platform mesh with its
# area perturbed by 1% produces a residual of 1.082e-05. The counter-test
# asserts a perturbed fixture exceeds this value, so widening
# PANEL_RECONSTRUCTION_RESIDUAL toward it eventually makes that test fail --
# which is the property that makes the ceiling defensible by execution rather
# than by argument. Seven orders separate the two.
# Set: 2026-08-30, F1
PANEL_RECONSTRUCTION_RESIDUAL_COUNTER: Final[float] = 1.0e-5



# ---------------------------------------------------------------------------
# Rung 1 -- The solver is a solver
# Rigid-body modes (G2.1/V1.1), patch test (G2.2/V1.2), unit scaling (G2.5/V1.3).
# These compare against exact algebraic results, so tolerances here are set by
# floating-point accumulation and conditioning, never by physical judgement.
# ---------------------------------------------------------------------------

# CLASS: ACCURACY -- carries TRANSFORM_INVARIANCE_COUNTER below.
# G2.5 / V2.4 -- agreement between the rotated response and the rotated local
# response. RELATIVE AND DIMENSIONLESS, scaled by the response itself:
#
#     |u_global - R u_local|  <=  TRANSFORM_INVARIANCE * ||u_local||_inf
#
# Reason: an orthogonal transform cannot change the response, so this is exact in
# exact arithmetic and the only admissible discrepancy is accumulation through a
# 12x12 triple product and a 6x6 solve. Measured worst-case over all six load
# DOF: 3.836e-15. 1e-11 sits ~4 orders above that floor.
#
# THE FORM MATTERS AS MUCH AS THE VALUE (AW1). An earlier draft used an ABSOLUTE
# atol on a displacement, which is a dimensional quantity: posing the same problem
# in millimetres moves the round-off floor by three orders while the tolerance
# stays put, so V1.3 (unit scaling) would either fail on this assertion or pass it
# vacuously. The offending component's exact value is also ZERO, where no absolute
# floor is meaningful at all -- which is why the first draft's 1e-18 failed against
# a measured 1.07e-18 for reasons unrelated to the transform. Scaling to
# ||u_local||_inf handles the zero components by the scale rather than by a floor.
# Set: 2026-09-02, F2
TRANSFORM_INVARIANCE: Final[float] = 1e-11

# COUNTER-CASE, measured IN THE SAME QUANTITY as the assertion (AW1).
# A _COUNTER is the smallest defect the SAME assertion detects, so it is measured
# on the displacement residual, not on the spectrum. Perturbing the correct
# rotation by the non-orthogonal I + [theta x] map gives a residual linear in
# theta: 1.227e-02 at 1e-3 rad, 1.228e-05 at 1e-6, 1.228e-07 at 1e-8. The
# counter is set at the last of these, so the gate must catch a non-orthogonality
# of TEN NANORADIANS -- four orders above the ceiling, and far below any
# first-order-rotation bug a real model could contain.
# Set: 2026-09-02, F2
TRANSFORM_INVARIANCE_COUNTER: Final[float] = 1.2e-7



# CLASS: ACCURACY -- carries TRANSFORM_SPECTRUM_INVARIANCE_COUNTER below.
# G2.5 / V2.4 -- relative agreement between eig(T^T K T) and eig(K), scaled by the
# largest eigenvalue. A separate entry from TRANSFORM_INVARIANCE because it is a
# DIFFERENT QUANTITY: the spectrum test is the only one that detects a
# non-orthogonal T without reference to any particular load case.
#
# Reason: an orthogonal similarity preserves eigenvalues identically. Measured
# shift under the real transform: 2.71e-16. 1e-11 sits ~5 orders above it.
# Set: 2026-09-02, F2
TRANSFORM_SPECTRUM_INVARIANCE: Final[float] = 1e-11

# COUNTER-CASE for the spectrum test, measured on the spectrum.
# The I + [theta x] trap shifts the spectrum by 1.30e-03 at theta = 0.05 rad,
# 5.20e-05 at 0.01, and 5.20e-07 at 0.001 -- so the gate must catch a first-order
# rotation of a milliradian.
# Set: 2026-09-02, F2
TRANSFORM_SPECTRUM_INVARIANCE_COUNTER: Final[float] = 5.0e-7



# CLASS: ACCURACY -- carries SUBDIVISION_INVARIANCE_COUNTER below.
# G2.2 / V1.2 -- relative agreement of a fixed-length cantilever's tip response
# across element counts. Dimensionless (a ratio of like quantities).
#
# Reason: the element is NODALLY EXACT for constant section and load, so
# subdividing changes nothing but round-off. Measured deviation from the
# one-element result: 9.99e-15 at n=2, 1.16e-14 at n=5, 4.58e-13 at n=11 -- and
# the per-solve equilibrium residual grows with it, 1.38e-14 to 8.79e-13 over the
# same range. That growth is a CONDITIONING signature, not a formulation error:
# more DOF means a longer factorisation chain. 1e-11 sits ~20x above the worst
# measured deviation, which leaves room for that growth at the mesh sizes F3 will
# use without admitting anything structural.
#
# DECLARED LATE (AW2). This value existed as an undeclared `rtol=1e-10` literal
# inside the test before it was measured, which is the local-literal failure this
# file exists to prevent.
# Set: 2026-09-02, F2
SUBDIVISION_INVARIANCE: Final[float] = 1e-11

# COUNTER-CASE, measured on the same quantity.
# A relative stiffness error in ONE member of the chain produces a tip deviation
# linear in it: 4.84e-04 at 1e-3, 4.85e-06 at 1e-5, 4.85e-08 at 1e-7. The counter
# is set at the last, so the gate must catch a one-part-in-10^7 error in a single
# element -- three orders above the ceiling.
# Set: 2026-09-02, F2
SUBDIVISION_INVARIANCE_COUNTER: Final[float] = 4.8e-8



# CLASS: ACCURACY -- carries PATCH_TEST_EXACTNESS_COUNTER below.
# G2.2 / V1.2 -- deviation of the interior nodal displacements from the exact
# constant-strain field, in a DISPLACEMENT-DRIVEN patch test on an irregular
# mesh. Relative, scaled by the largest component of the exact field, so it is
# dimensionless and survives V1.3's unit rescaling.
#
# Reason: the six constant-strain states -- axial, twist, and curvature and
# constant shear in EACH bending plane -- are reproduced EXACTLY by this element,
# not in the limit, so the only admissible deviation is round-off. Measured over
# all six, on the shipped solve path:
#
#   axis-aligned   1.87e-16 .. 3.88e-15
#   skew straight  4.80e-16 .. 1.25e-14   (transform accumulation)
#
# 1e-12 sits 80x above the worst of those, which covers the transform path and
# longer chains, and 5 orders below the counter-case.
#
# OPERATING POINT OF THE 80x, because a ratio carries one or it carries nothing
# (ninth guard). It belongs to ONE geometry: tube D = 0.6 m, t = 0.012 m, element
# lengths 0.79 .. 3.27 m, i.e. a longest-element slenderness L/r = 15.7. The
# ceiling is breached by slender members. Sweeping the section at constant
# D/t = 50 and re-running all six states in both orientations:
#
#   D (m)   elem L/r   worst err   x ceiling
#    0.60      15.7    1.251e-14      0.013
#    0.40      23.6    3.807e-14      0.038
#    0.20      47.2    1.571e-13      0.157
#    0.10      94.4    1.762e-12      1.762   BREACH
#    0.05     188.7    4.415e-12      4.415   BREACH
#    0.02     471.8    1.844e-11     18.440   BREACH
#
# THERE IS NO BOUNDARY, and the one this comment carried is WITHDRAWN (R46).
# It read "bisected, the boundary is D = 0.0791 m, element L/r = 119" while the
# table three lines above records D = 0.10 as a breach -- self-contradictory in
# one block. The number was carried from a verdict rather than regenerated. A
# finer sweep shows the quantity is NOT MONOTONE in slenderness:
#
#   L/r      78.6    85.8    94.4    99.3   111.0   117.9   125.8
#   err   1.01e-12 2.27e-13 1.76e-12 4.64e-13 8.03e-13 1.03e-12 8.97e-13
#            B                 B                          B
#
#   (The reviewer records 5.662e-13 at L/r = 111.0 where this run gives
#    8.031e-13, on the same code and the same section. The discrepancy is not
#    resolved and is recorded rather than averaged away; it is one more sample of
#    the scatter this block is about.)
#
# Breaches with clean points between them, so bisection measures nothing: two
# runs of it on the same predicate returned L/r = 93.3 and L/r = 119.
#
# WHY, by the cell that isolates it (BG0). The fill-reducing permutation of the
# factorisation CANNOT change the exact solution -- it changes only the order the
# arithmetic happens in. Moving that one variable and holding everything else:
#
#   D      L/r     COLAMD      NATURAL     MMD_ATA   MMD_AT_PLUS_A   spread
#   0.600  15.7  1.25e-14 rz  7.97e-15 rz  1.02e-14 rz  2.11e-14 rz   2.65x
#   0.120  78.6  1.01e-12 rz  6.20e-13 rz  2.88e-13 rz  5.12e-13 rz   3.51x
#   0.100  94.4  1.76e-12 rz  9.92e-13 rz  1.08e-12 ry  5.72e-13 rz   3.08x
#   0.080 117.9  1.03e-12 ry  1.53e-12 rz  8.46e-13 ry  6.72e-13 rz   2.27x
#
# The magnitude moves by 2.3x to 3.5x and the worst COMPONENT changes between rz
# and ry, on a change that provably cannot move the answer. **The residual field
# is round-off, not the element**, and whether a given section "breaches" is
# decided by the pinned `SPARSE_PERMC_SPEC`. At D = 0.12, MMD_ATA turns the
# breach into 2.88e-13.
#
# Where it sits: entirely on the SKEW orientation, in the AXIAL state, worst
# component a ROTATION whose exact value is identically zero (axis-aligned stays
# at 1.1e-16 in that state). The denominator is the axial state's own weighted
# maximum, 8.94e-04, which contains no rotational content at all, so the ratio is
# an amplified round-off over an unrelated scale.
#
# NOT the amplitude: scaling EPS_AXIAL over four decades leaves the ratio flat to
# 1.3x, which is guaranteed by linearity and therefore discriminates nothing.
# That cell was run first and is recorded as vacuous rather than as evidence.
#
# The sweep convention matters and is stated: at FIXED wall t = 0.012 m the same
# diameters give 6.42e-13 at D = 0.10 and no breach until D = 0.05, because a
# thick-walled small tube is not slender. D/t = 50 holds the section's proportions
# and is the sweep that isolates slenderness.
#
# UNIT SYSTEM, ASSERTED BY THE SHIPPED TEST (R40). The gate runs at
# S = 1e-3, 1, 1e3 -- 36 nodes -- so the number below is produced by pytest, not
# by a harness. Worst over six states x two orientations at each:
#
#   S = 1e-3   axis-aligned 1.150e-14   skew 1.603e-13   <- worst, 6.2x headroom
#   S = 1      axis-aligned 3.883e-15   skew 1.251e-14   <- 80x
#   S = 1e+3   axis-aligned 8.858e-15   skew 4.924e-14
#
# OUT OF BAND, measured but NOT asserted by any test: across S = 1e-4 .. 1e+4 the
# worst is 2.00e-13 and there is no breach; from 1e-8 to 1e+8 the reviewer
# measured 2.4e-13. Those figures are context for how far the property extends,
# and they are labelled as unasserted because the previous version of this
# comment let a scratch-harness number carry the ceiling.
#
# WHAT CLOSED IT, measured by ablation (R8). An earlier version of this comment
# said the invariance "required two fixes". All four cells, worst error over the
# six states at each S:
#
#   equilibrate   weighted measure   worst err    breaches of 1e-12
#      yes              yes           3.19e-14         none
#      NO   <- ships    yes           2.00e-13         none
#      yes              NO            2.09e-11    S = 1e-4, 1e-3, 1e4
#      NO               NO            2.07e-10    S = 1e-4, 1e-3, 1e3, 1e4
#
# The ERROR MEASURE alone is necessary and sufficient. Taking max() across all six
# DOF mixes metres with radians, so the measure was unit-dependent on its own; a
# spurious rotation divided by a translational scale grows with S while the solve
# is untouched. Weighting rotations by a characteristic length fixes it.
#
# EQUILIBRATION IS NOT ON THE SOLVE PATH (BD2). It was, for two commits, and this
# comment described that configuration for two more: the "3.19e-14 across all
# scales", the retention argument, and the floor below all belonged to a path
# `solve` no longer takes. Row 2 is what ships. Equilibration remains a tested
# utility -- cond(K~) = 3.85e2 at every unit system is real and asserted -- and
# `floatfea/assemble/system.py` carries why it is not in the solve.
#
# FLOOR. There is no single conditioning floor on the shipped path, because
# cond(K_ff) is a property of the unit system: it runs 9.21e2 at S = 1 to 5.98e10
# at S = 1e-4, so cond(K_ff) * eps spans 2.05e-13 .. 1.33e-05. The measured error
# does NOT track that bound -- err / (cond * eps) is 0.061 at worst and below
# 0.01 at seven of the nine scales -- so this ceiling is justified by measurement
# across the range, not by a conditioning estimate. At the metre scale where the
# gate is posed, cond(K_ff) * eps = 2.05e-13 and the ceiling is 4.9x it.
#
# THIS IS AN EXACTNESS TOLERANCE, NOT A CONVERGENCE ONE. An element that
# reproduces constant curvature only in the limit is passing a convergence test
# wearing the patch test's clothes; there is nothing between exact and wrong here,
# which is why the value sits at ULP scale rather than at an engineering one.
# Set: 2026-09-02, F2
PATCH_TEST_EXACTNESS: Final[float] = 1e-12

# COUNTER-CASE, measured on the same quantity and in the WORST state.
# A relative stiffness error in ONE interior element perturbs the interior field
# linearly: at 1e-6 the four states move by 1.09e-07 (axial), 1.09e-07 (twist),
# 3.72e-08 (curvature) and 3.02e-08 (shear). The counter is set at the SMALLEST
# of those, so every state must catch a one-part-in-10^6 stiffness error, not
# merely the most sensitive one.
#
# TIGHTENED 2026-09-03, from 3.0e-8, under the dimensionally homogeneous error
# measure (R2). The assertion is `err >= COUNTER`, so raising it makes the negative
# control STRICTER, not weaker. Under the old mixed-unit measure the bending
# states' rotational error was divided by a translational scale and thereby
# understated at 3.72e-08 and 3.02e-08; measured coherently all six states respond
# at 1.08e-07 .. 1.17e-07 and the counter moves to the smallest of those.
#
# Its earlier history: 6.0e-9 came from a mesh containing 0.9/0.6 = 3/2 exactly.
# The claim that changing that mesh bought a fivefold improvement is WITHDRAWN --
# controlled measurement puts commensurability at nothing, the ratio to a
# uniform mesh straddling 1 across draws (0.85-1.09). The value
# moved because the perturbed element's length and position changed with it. See
# docs/instrumentation.md, seventeenth guard.
# Set: 2026-09-03, F2
PATCH_TEST_EXACTNESS_COUNTER: Final[float] = 1.0e-7



# CLASS: ACCURACY -- carries PATCH_TEST_COND_FACTOR_COUNTER_DEFECT below.
# G2.2 / V1.2 -- the FLOOR-AWARE half of the patch-test ceiling, in multiples of
# the accuracy the solve can achieve on the problem posed:
#
#     err <= PATCH_TEST_COND_FACTOR * cond(D^-1/2 K_ff D^-1/2) * eps
#
# Dimensionless. Asserted ALONGSIDE PATCH_TEST_EXACTNESS, never instead of it.
#
# THE FLOOR IS THE EQUILIBRATED CONDITIONING (BH1/R55), and the first version of
# this entry got that wrong. It used cond(K_ff), which is not unit-invariant --
# and the gate runs three unit systems:
#
#   S        cond(K_ff)     cond(K~)    worst err   err/(c~.eps)
#   1e-3     5.9831e+08   3.8491e+02   1.6029e-13       1.8754
#   1        9.2096e+02   3.8491e+02   1.2513e-14       0.1464
#   1e+3     4.0490e+07   3.8491e+02   4.9240e-14       0.5761
#
# cond(K~) is the SAME NUMBER at all three -- spread 1.000000x -- because
# diag(SKS) = S diag(K) S makes the equilibrated matrix invariant under a
# diagonal rescaling. A ceiling built on cond(K_ff) was 5.4e5x weaker at
# millimetres than at metres: it scaled with the unit system, not the problem.
#
# AND IT KEEPS THE OTHER PROPERTY. cond(K~) still tracks slenderness -- 121.7x
# over D = 0.6 .. 0.05 -- so it is not a constant wearing a floor's clothes:
#
#   D      L/r    cond(K_ff)    cond(K~)   worst err   err/(c~.eps)
#   0.600  15.7    9.210e+02   3.849e+02   1.251e-14      0.1464
#   0.200  47.2    7.631e+03   2.859e+03   1.571e-13      0.2476
#   0.120  78.6    2.105e+04   7.929e+03   1.010e-12      0.5739
#   0.100  94.4    3.028e+04   1.148e+04   1.762e-12      0.6912
#   0.080 117.9    4.727e+04   1.807e+04   1.028e-12      0.2561
#   0.050 188.7    1.209e+05   4.684e+04   4.415e-12      0.4245
#
# Against the constant those same errors span 141x and cross 1 three times
# non-monotonically; against this floor they span 7.9x and never reach 1.
#
# THE FACTOR, and it covers the round-off scatter rather than ignoring it. The
# worst ratio over 3 scales x 2 orientations x 6 states x FOUR fill-reducing
# permutations is 1.8754 -- the permutation cannot change the exact answer, so
# its spread (1.9x .. 2.9x per scale) is round-off and belongs inside the
# measurement. 8.0 sits 4.3x above that worst cell. At the posed geometry the
# ceiling is 8.0 * 3.8491e2 * 2.22e-16 = 6.838e-13, TIGHTER than the 1e-12 it
# accompanies, so the floor-aware term binds there and nothing is loosened.
#
# THE SELF-REFERENCE IS BOUNDED, NOT DENIED (BH2). This ceiling is computed from
# the same K the gate tests, so a defective K moves it. The first version of this
# entry said "the ceiling moves by at most 1.13x under any defect the gate must
# catch" -- measured against three defects its own author chose, and refuted by a
# UNIFORM J x 0.01, which is the class the neighbouring blindness test declares
# invisible.
#
# THE CELL, and it also measures what BH1 bought. One variable moved -- which
# conditioning the floor uses -- everything else held:
#
#   defect        cond(K_ff)    move     cond(K~)    move
#   clean         9.2096e+02      --   3.8491e+02      --
#   J x 0.01      5.9831e+04   65.0x   2.0847e+03    5.4x
#   J x 100       3.0630e+03    3.3x   5.5615e+02    1.4x
#   A x 0.01      4.5522e+02    0.5x   5.9826e+01    0.2x
#
# The 65x that refuted the old claim is the UNEQUILIBRATED floor. Equilibrating it
# (BH1) damps the same defect to 5.4x -- a 12x reduction that was not the reason
# for that change and is measured here rather than claimed for it.
#
# THE DEFENCE IS THE CAP, not an assertion that it cannot move.
# PATCH_TEST_EXACTNESS is asserted beside this term, so the effective ceiling is
# min(constant, floor-aware) and the loosening ANY defect can buy is bounded by
# constant / binding_clean. Measured over the admitted corpus:
#
#   worst bound, over every admitted entry            5.313x
#   every slender entry, where floor-aware > constant 1.000x  (no loosening at all)
#   the posed geometry                                1.463x
#
# And under the J x 0.01 defect the floor-aware term moves 5.4x while the BINDING
# ceiling moves 1.463x. Detection survives inside that bound: the counter defect's
# response is 3.23e-11 .. 3.52e-11 clean and 3.23e-11 .. 3.52e-11 with J x 0.01
# applied, against a binding ceiling of 1.0e-12 -- every state still fires.
# Set: 2026-09-04, F2
PATCH_TEST_COND_FACTOR: Final[float] = 8.0

# COUNTER-CASE, a DEFECT SIZE (BG1). Measured by bisecting the shipped predicate
# for the smallest single-element relative stiffness defect it detects, PER STATE
# because the counter must be caught by every state and not only the most
# sensitive:
#
#   D      L/r    ceiling      axial  curvature      twist      shear   curv_xz   shear_xz
#   0.600  15.7  6.838e-13  6.273e-12  6.316e-12  6.270e-12  5.728e-12  6.355e-12  5.802e-12
#   0.120  78.6  1.409e-11  1.302e-10  1.295e-10  1.291e-10  1.194e-10  1.305e-10  1.213e-10
#   0.100  94.4  2.039e-11  1.883e-10  1.886e-10  1.869e-10  1.751e-10  1.888e-10  1.752e-10
#   0.080 117.9  3.210e-11  2.933e-10  2.966e-10  2.943e-10  2.761e-10  2.983e-10  2.773e-10
#
# The counter is set just above the worst cell, 2.983e-10. Ceiling and threshold
# move together, so doubling the factor pushes the threshold past the counter and
# the counter test goes red -- which is what makes silent widening impossible
# rather than reviewed-for.
# Set: 2026-09-04, F2
PATCH_TEST_COND_FACTOR_COUNTER_DEFECT: Final[float] = 3.0e-10


# CLASS: ACCURACY -- carries SOLVE_BACKWARD_ERROR_FACTOR_COUNTER_DEFECT below.
# Rung 1 -- the solve's BACKWARD ERROR, in multiples of eps:
#
#     ||K u - f|| / (||K||_max ||u||_2 + ||f||_2)  <=  FACTOR * eps
#
# Dimensionless. This is how large a perturbation of the system the computed
# solution solves exactly, and for a backward-stable factorisation it is a small
# multiple of eps whatever the scaling of the problem.
#
# WHY NOT ||r|| / ||f||, WHICH THIS REPLACES (R45). That normalisation was gated
# at 1e-13 and restricted to metres on the recorded ground that "the residual is
# conditioning-limited, and cond(K_ff) is a property of the unit system". THE
# CELL REFUTES IT. cond(K_ff) is a property of the MATRIX, so it is identical for
# all six states at a scale; holding it fixed and varying the state:
#
#   state          S=1e-3 r/f    bwd      K.u/f        S=1 r/f     bwd
#   axial            3.54e-16  6.17e-17  4.7e+00      5.93e-16  1.03e-16
#   curvature        1.93e-15  1.54e-19  1.3e+04      1.06e-15  3.09e-17
#   twist            2.30e-13  1.62e-21  1.4e+08      1.47e-15  1.02e-17
#   shear            2.49e-15  2.20e-19  1.1e+04      1.73e-15  4.73e-17
#   curvature_xz     2.12e-15  1.69e-19  1.3e+04      7.47e-16  2.18e-17
#   shear_xz         1.96e-15  1.73e-19  1.1e+04      1.14e-15  3.11e-17
#
# Five of six states at S = 1e-3 sit at round-off at the very conditioning that
# was blamed. The whole excursion is the `twist` cell, whose ||K||.||u||/||f|| is
# 1.4e+08 against 4.7 for axial -- a collapsing LOAD norm, not conditioning.
#
# Reason for the value: the worst backward error over all eighteen cells the gate
# runs is 1.0343e-16, which is 0.47 eps. 8.0 sits 17x above it, and the whole
# spread across the eighteen is 1.62e-21 .. 1.03e-16 -- so the ceiling is bounded
# by the arithmetic rather than by any property of the load case, which is the
# point of the change. It is asserted at ALL THREE unit scales, where the
# quantity it replaces could only be asserted at one.
# Set: 2026-09-04, F2
SOLVE_BACKWARD_ERROR_FACTOR: Final[float] = 8.0

# COUNTER-CASE, a DEFECT SIZE (BG1): the relative error in the solved field that
# must still push the backward error above the ceiling. Measured by bisection on
# the shipped predicate, per cell -- and it is strongly configuration-dependent,
# which is the cost of this normalisation and is recorded rather than buried:
#
#   worst cell (twist, S = 1e-3, where ||K||.||u||/||f|| = 1.4e8)   see below
#   best  cell (axial, S = 1,    where ||K||.||u||/||f|| = 4.7)
#
# The counter is set above the WORST cell so every cell catches it. NOTE the
# trade this makes explicit: ||r||/||f|| detected a wrong solve at ~1e-12, and
# this detects one at the value below. Backward error is the right measure of
# STABILITY and a weaker detector of a WRONG ANSWER on a badly scaled system;
# both are now reported by `SolveResult` and only this one is gated.
# Set: 2026-09-04, F2
SOLVE_BACKWARD_ERROR_FACTOR_COUNTER_DEFECT: Final[float] = 1.0e-6


# CLASS: ACCURACY -- carries RESULTANT_EXACTNESS_COUNTER below.
# G2.2 / V1.2 -- deviation of the RECOVERED element end forces from the analytic
# resultants of the constant-strain state: EA*eps, EI*kappa in each bending plane,
# GJ*phi', and for state 4 the constant shear P with its linear moment P(L-x).
# Relative, scaled per element by the largest analytic resultant of that element,
# so it is dimensionless.
#
# A SEPARATE ENTRY FROM PATCH_TEST_EXACTNESS BECAUSE IT IS A DIFFERENT QUANTITY.
# The displacement check compares a field; this compares a stiffness-weighted
# FIRST DIFFERENCE of that field, so it loses two to three digits to cancellation
# and cannot share a ceiling. Reusing the displacement ceiling for a quantity of
# another kind is what made the solve-residual line it replaces unfalsifiable
# (R41) -- that line sat at 1e-15 against a 1e-12 ceiling and did not move under a
# defect that failed the displacement check by eleven orders.
#
# Reason: exact in exact arithmetic -- the states are reproduced exactly, so the
# recovered forces are the analytic ones. Measured worst over six states x two
# orientations, on the shipped path:
#
#   S = 1e-3   axis-aligned 2.892e-11   skew 4.558e-11   <- worst
#   S = 1      axis-aligned 1.525e-13   skew 3.921e-13
#   S = 1e+3   axis-aligned 2.900e-13   skew 1.484e-12
#
# 1e-9 sits 22x above the worst of those and ~700x below the counter-case.
#
# OPERATING POINT, because a ratio against a varying denominator carries one or it
# carries nothing (ninth guard). These are the scales the shipped test runs
# (S = 1e-3, 1, 1e3) at the posed geometry, tube 0.6/0.012, element lengths
# 0.79..3.27 m. The error tracks the conditioning of the solve rather than the
# element: outside that band it grows to 7.2e-10 at S = 1e-4, where
# cond(K_ff) = 6.0e10. The ceiling is claimed over the band the test runs, not
# beyond it.
# Set: 2026-09-04, F2
RESULTANT_EXACTNESS: Final[float] = 1e-9

# COUNTER-CASE, measured on the same quantity and in the WORST state.
# A 1e-6 relative stiffness error in ONE interior element moves the recovered
# resultants by 6.898e-07 (axial, twist), 6.934e-07 (both curvature states) and
# 7.983e-07 (both shear states). The counter is set just below the SMALLEST, so
# every state must catch a one-part-in-10^6 stiffness error through the forces as
# well as through the displacements.
#
# WHAT THIS CHANNEL IS FOR, corrected (R47). An earlier version of this entry
# said the resultant channel is "~6.4x the more sensitive", from the ratio of raw
# responses to one 1e-6 defect (6.90e-07 against 1.08e-07). That is a RESPONSE
# ratio standing where a DECISION ratio is meant, and the two channels are
# compared against ceilings a thousand times apart. Inverting each shipped
# predicate instead -- the smallest single-element stiffness defect each one
# actually detects:
#
#   state            via field  via resultants    ratio
#   axial           9.1808e-12      1.4498e-09   157.9x
#   curvature       9.2518e-12      1.4422e-09   155.9x
#   twist           9.1708e-12      1.4498e-09   158.1x
#   shear           8.4540e-12      1.2527e-09   148.2x
#   curvature_xz    9.2976e-12      1.4422e-09   155.1x
#   shear_xz        8.4953e-12      1.2527e-09   147.5x
#
# As a gate it is ~150x WEAKER, not 6.4x stronger. It is kept for what it sees
# rather than for sensitivity: a different quantity, checked against statics
# rather than against the solve, catching four of five planted sign defects in
# its own analytic table. NOTE against that claim (R53): with I_y == I_z forced
# by every shape `basis.kappa` knows, it cannot see an I_y/I_z swap either.
# Set: 2026-09-04, F2
RESULTANT_EXACTNESS_COUNTER: Final[float] = 6.8e-7


# CLASS: ACCURACY -- carries MATRIX_SYMMETRY_COUNTER below.
# G2.1 / V1.1 -- symmetry of an assembled or element stiffness matrix, relative,
# scaled by the largest entry. Dimensionless.
#
# Reason: K is symmetric in exact arithmetic (Maxwell-Betti), so the only
# admissible asymmetry is accumulation through the 12x12 triple product and the
# scatter-add. Measured on the element and on a 5-member assembly: max |K - K^T|
# / max |K| is 0.0 exactly for a single element and 2.4e-16 assembled. 1e-9 sits
# ~7 orders above that, which covers longer chains without admitting a
# transposed block (which shows at O(1)).
# Set: 2026-09-03, F2
MATRIX_SYMMETRY: Final[float] = 1e-9

# COUNTER-CASE: a MIS-INDEXED SCATTER -- the element's columns landing on the
# wrong node's DOF while its rows land correctly. Measured on a 5-member frame:
# max |K - K^T| / max |K| = 7.902e-02, eight times the ceiling.
#
# CORRECTED BY INJECTING IT (BG1). This entry said the defect was "one transposed
# element block ... 3.1e-01". An element contribution is SYMMETRIC
# (max|kg - kg^T| / max|kg| = 3.7e-17), so transposing one is a no-op: the
# assembly's asymmetry stays at 3.711e-17, which is its clean value. The named
# defect was not a defect, and nothing ran it for four rounds. Measured
# alternatives, on the same frame:
#
#   transpose the block (the named defect)   3.7107e-17   <- no-op, = clean
#   columns scattered to the wrong node      7.9020e-02   <- the counter
#   upper triangle only                      5.0000e-01
#   one off-diagonal entry, 5%               2.5000e-02
#
# The value 1e-2 stands on the second and third rows. Only the sentence moved.
# Set: 2026-09-03, F2; basis corrected 2026-09-04
MATRIX_SYMMETRY_COUNTER: Final[float] = 1.0e-2



# CLASS: ACCURACY -- carries ROUNDOFF_IDENTITY_COUNTER below.
# Rung 1 -- relative agreement for a property that is EXACT in exact arithmetic
# and is asserted at round-off: triad orthonormality, reciprocity of a
# flexibility matrix, the equality of two algebraically identical expressions.
# Dimensionless in every use.
#
# Reason: these have no discretisation error to bound, only floating-point
# accumulation. Worst measured across its nine sites is 2.2204e-16 -- one ULP.
# 1e-14 sits ~45x above that.
#
# SET BY THE TIGHTEST MEMBER OF THE GROUP (BD1). It was briefly 1e-12, which was
# a 100x WIDENING of three sites that had carried 1e-14 and measured 3.7e-17 ..
# 1.9e-16 -- 53x to 267x of headroom, and nothing forcing the change. That was
# done while the commit message asserted no value had been loosened. When a group
# of literals is consolidated the new entry takes the tightest member, or the
# group splits; it never takes a round number chosen for looking tidy.
# Set: 2026-09-03, F2
ROUNDOFF_IDENTITY: Final[float] = 1e-14

# COUNTER-CASE: the smallest defect these assertions must still catch. A single
# sign error or a swapped index in any of the quantities involved is O(1); the
# subtlest real case is the non-orthogonal I + [theta x] first-order map, whose
# orthonormality deviation is O(theta^2) because the map is orthogonal to first
# order: ``M^T M - I = K^T K``. Measured:
#
#   theta      ||M^T M - I||_max     theta^2
#   1e-08          5.7022e-17         1.0e-16
#   1e-06          1.5019e-12         1.0e-12
#   1e-04          1.5018e-08         1.0e-08     <- the counter
#   1e-02          1.5018e-04         1.0e-04
#
# CORRECTED BY INJECTING IT (BG1). This entry said the 1e-08 deviation came from
# "theta = 1e-8", which is wrong by EIGHT ORDERS -- at that angle the deviation is
# 5.7e-17, i.e. round-off. The value stands; the angle that produces it is 1e-4.
# Set: 2026-09-03, F2; basis corrected 2026-09-04
ROUNDOFF_IDENTITY_COUNTER: Final[float] = 1.0e-8



# CLASS: ACCURACY -- carries COND_UNIT_INVARIANCE_COUNTER below.
# G2.5 / V1.3 -- relative agreement of cond(D^-1/2 K D^-1/2) between two unit
# systems. Dimensionless.
#
# Reason: equilibration makes the conditioning algebraically invariant under a
# diagonal rescaling, so this is exact in exact arithmetic; measured agreement
# across S = 1e-3 .. 1e+3 is within 1e-11. 1e-6 leaves room for the eigenvalue
# computation on an ill-conditioned unequilibrated input without admitting a real
# drift.
#
# DECLARED LATE (R13). This was a bare `rel=1e-6` inside the test, written two
# commits after AW2 closed on exactly that defect.
# Set: 2026-09-03, F2
COND_UNIT_INVARIANCE: Final[float] = 1e-6

# COUNTER-CASE: without equilibration cond(K_ff) spans 6.5e5 across the same unit
# systems, so the assertion must catch anything at or above that ratio; the
# counter is set far below it, at the smallest drift worth investigating.
# Set: 2026-09-03, F2
COND_UNIT_INVARIANCE_COUNTER: Final[float] = 1.0e-3



# CLASS: ACCURACY -- carries DETECTION_THRESHOLD_BAND_COUNTER below.
# G2.2 / V1.2 -- how closely a perturbation AT a recorded detection threshold must
# reproduce the ceiling. Relative, dimensionless.
#
# Reason: the thresholds are computed as TOL/sensitivity, so perturbing by one
# should land the error on TOL exactly; the deviation is the departure from
# linearity over that range. Worst measured across the six states: 9.9523e-03.
# 0.05 sits 5x above it -- enough that linearity's own curvature does not trip the
# check, tight enough that a real change in sensitivity does.
#
# DECLARED LATE. This was R13's THIRD bare literal, and the regex scanner it was
# reported against read the line as clean because a tolerance NAME appeared
# elsewhere on it (`pytest.approx(PATCH_TEST_EXACTNESS, rel=0.05)`). The AST
# scanner checks the argument node, so the hole is closed by construction.
# Set: 2026-09-03, F2
DETECTION_THRESHOLD_BAND: Final[float] = 0.05


# COUNTER-CASE: a sensitivity change large enough to matter. If a formulation
# change moved any state's sensitivity by 25%, perturbing by the recorded
# threshold would miss the ceiling by that much and this must catch it.
# Set: 2026-09-03, F2
DETECTION_THRESHOLD_BAND_COUNTER: Final[float] = 0.25


# ---------------------------------------------------------------------------
# Rung 2 -- The element is the element it claims to be
# Cantilever slender/stubby (G2.3/V2.1-2.2), torsion (V2.3), 3D coupling (V2.4),
# free-free frequencies (G2.4/V2.5), releases and rigid links (V2.6).
# Compared against closed-form textbook solutions.
# ---------------------------------------------------------------------------

# (no entries yet -- F2)


# ---------------------------------------------------------------------------
# Rung 3 -- The model is the platform
# Mass correctness (G3.1a/V3.1a), mass consistency (G3.1b/V3.1b), YAML
# round-trip (G3.2/V3.2), exact section properties (G3.3/V3.3).
#
# Note G3.1b is the convergence criterion of a design loop, not a code gate --
# see PLAN.md sec.6 F3. Its tolerance expresses "close enough that the analysed
# loads are representative", which is a different kind of claim from every other
# entry in this file and must say so in its comment.
# ---------------------------------------------------------------------------

# (no entries yet -- F3)


# ---------------------------------------------------------------------------
# Rung 4 -- The loads are the loads
# Equilibrium residual (G4.1/V4.1), rigid-body acceleration (G4.2/V4.2),
# hydrostatic (G4.3/V4.3), mapping conservation (G4.4), residual convergence
# rate (G4.5), hydrostatic reconciliation (G4.6), frame round-trip (V4.4),
# strip integration (V4.5), reconstruction integrity (G1.6).
#
# G4.1's tolerance must NOT be set above the timestamp-alignment floor. The
# exporter aligns each force to the index of the state it was evaluated from,
# which removes an O(omega*dt) ~ 3.2% residual at full scale; declaring that
# floor instead would put the tolerance at precisely the level that hides a real
# load-path defect. G4.5 guards the alignment by convergence RATE, not by
# magnitude. See docs/milestones/F1.md sec.6 and PLAN.md sec.8.
# ---------------------------------------------------------------------------

# (no entries yet -- F1/F4)


# ---------------------------------------------------------------------------
# Rung 5 -- Independent confirmation
# CalculiX global cross-check (G7.1/V5.1), stress recovery (G6.2/V5.2), code
# check hand calculations (G6.1/V5.3).
#
# G7.1's values are stated in PLAN.md sec.6 F7 (0.5% displacement, 1% member
# force). An exceedance is explained in writing before the milestone closes --
# never absorbed here.
# ---------------------------------------------------------------------------

# (no entries yet -- F6/F7)


# ---------------------------------------------------------------------------
# Rung 6 -- It stays fixed
# Golden-file regression (V6.1). A golden-file change requires a written
# explanation of why the numbers moved, in the milestone closure artifact.
# ---------------------------------------------------------------------------

# (no entries yet -- F6)
