"""The exemption corpus's figures, measured at the commit that publishes them.

R353. Two counts lived in comments in `tests/test_marker_exemption_corpus.py`
and `7ba1e9d` moved one entry across the boundary they count, the commit
after they were written. Both were true when written and neither was
re-taken. That is BP0, and it is the same species as R341's second half --
in the same file, in the round that repaired it.

A comment is a report nothing regenerates. These figures are produced here
and published in the step report, which is regenerated by rule, and this
script runs after every other edit to a revision, like `suite_count.py`.

WHAT EACH NUMBER IS:

    entries           entry headers in the reviewer's corpus file, counted
                      by `_headers_in_the_file()` -- the reader that exists
                      to disagree with the parser (R351)
    asserted          shapes the scanner did the right thing about at plant
                      time. These are the regression domain: if one of them
                      escapes now, something moved under it
    recorded escapes  shapes the scanner did the WRONG thing about at plant
                      time. Allowed growth, derived from `measured=`
    improved          recorded escapes the scanner now catches. Improvement,
                      countable, and it needs no ceremony to record

Usage:

    python scripts/corpus_figures.py
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
# Both: `tests/` for the corpus reader, the root for `floatfea` itself,
# which the scanner imports to learn the declared tolerance names.
sys.path.insert(0, str(ROOT / "tests"))
sys.path.insert(0, str(ROOT))

# The import is by path, not by package: `tests/` is not importable as one.
from test_marker_exemption_corpus import (  # type: ignore[import-not-found]  # noqa: E402
    ASSERTED,
    ENTRIES,
    PLANTED_ESCAPES,
    _headers_in_the_file,
    _measured_misses,
)


def main() -> int:
    sys.stdout.reconfigure(encoding="utf-8")  # type: ignore[union-attr]
    improved = PLANTED_ESCAPES - _measured_misses()
    rows = [
        ("entry headers in the corpus file", _headers_in_the_file()),
        ("entries that reached the assertions", len(ENTRIES)),
        ("asserted -- the regression domain", len(ASSERTED)),
        ("recorded escapes -- allowed growth", len(PLANTED_ESCAPES)),
        ("of those, caught now -- improvement", len(improved)),
    ]
    width = max(len(label) for label, _ in rows)
    for label, value in rows:
        print(f"{label.ljust(width)}  {value}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
