#!/usr/bin/env python
"""The whole-suite count a step report must carry (CI1, R309).

    python scripts/suite_count.py >> the report

A report published seven subset counts, every one of them correct, while the
suite was red on a test in none of the seven -- and the failing declaration had
been written by the commit that published the report, so it was true when it
was measured and false when it shipped. `CLAUDE.md` § Step gating asks for "the
test counts from your own run"; seven subsets are not that, because the
collection the evidence inspects cannot contain the failure.

This runs the WHOLE suite, once, and prints one line with the three numbers and
the commit it ran at, plus a named list of anything that failed or was skipped.
`tests/test_report_carried.py` fails a report that does not carry the line, and
fails one that carries a non-zero failure count without naming a test.

RUN IT LAST. Every other edit to the report goes in first: the count is a
measurement of the tree the report is committed from, and an edit after it is
an edit the number does not describe. That ordering is the whole content of
R309 -- the declaration it missed was added in the same commit as the report.
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path
from xml.etree import ElementTree

ROOT = Path(__file__).resolve().parents[1]


def _sha() -> str:
    out = subprocess.run(
        ["git", "rev-parse", "--short", "HEAD"], cwd=ROOT, capture_output=True, text=True
    )
    return out.stdout.strip() or "unknown"


def run(report: Path) -> tuple[int, int, int, list[str], list[str]]:
    """`(passed, failed, skipped, failing ids, skipped ids)` from junit."""
    subprocess.run(
        [sys.executable, "-m", "pytest", "-q", "-p", "no:randomly", f"--junit-xml={report}"],
        cwd=ROOT,
        capture_output=True,
        text=True,
    )
    root = ElementTree.parse(report).getroot()
    failed: list[str] = []
    skipped: list[str] = []
    total = 0
    for case in root.iter("testcase"):
        total += 1
        name = f"{case.get('classname', '')}::{case.get('name', '')}".strip(":")
        kinds = {kid.tag for kid in case}
        if kinds & {"failure", "error"}:
            failed.append(name)
        elif "skipped" in kinds:
            skipped.append(name)
    return total - len(failed) - len(skipped), len(failed), len(skipped), failed, skipped


def main(argv: list[str]) -> int:
    sys.stdout.reconfigure(encoding="utf-8")
    out = ROOT / ".suite.xml"
    passed, failed, skipped, failing, skips = run(out)
    out.unlink(missing_ok=True)
    sha = _sha()
    print(
        f"**Whole suite at `{sha}`: {passed} passed, {failed} failed, "
        f"{skipped} skipped.** Generated by `python scripts/suite_count.py`, "
        "run after every other edit to this revision."
    )
    if failing or skips:
        print()
        for name in failing:
            print(f"- **failed** `{name}`")
        for name in skips:
            print(f"- **skipped** `{name}`")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
