"""G1.6 in CI — the panel-reconstruction identity as a normal test (AN2).

Why this exists
---------------
G1.6 was the **only** gate whose evidence was a script in `artifacts/` rather than
a test, while the closure artifact claimed every gate fails a build when broken.
An exception is where rot starts, and this is the gate with the longest and most
subtle history in the project.

The identity is **size-independent**:

    F_j = -sum_p  p_p (n_p . d_j,p) A_p    ==    w^2 A_jk + i w B_jk

so it does not need the 12-buoy platform. The committed fixture is two spheres,
64 wetted panels, 12 DOF, one frequency — seconds to generate, 13.6 kB to store,
and it pins exactly the arithmetic the full run measures at `1.308e-15`.

What this does NOT cover, since the scalar does not carry it
------------------------------------------------------------
* **One frequency.** The identity holds per-frequency; this pins the arithmetic,
  not the frequency dependence.
* **`rotation_center` coincides with the moment reference** in the fixture. On
  the real platform they differ, and that transformation belongs to F4's mapping.
* **Quadrature is not covered here** — under AF3 it is common-mode by
  construction and is guarded in HSP (see AK1 in the closure artifact).

Fixture: `tests/fixtures/panel_reconstruction.npz`, generated by
`artifacts/make_panel_fixture.py`. It is a **golden file**: regenerating it
requires a written explanation of why the numbers moved.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pytest

from floatfea.io.frames import live_dof, over_live
from floatfea.tolerances import (
    PANEL_RECONSTRUCTION_RESIDUAL,
    PANEL_RECONSTRUCTION_RESIDUAL_COUNTER,
)

FIXTURE = Path(__file__).resolve().parents[2] / "fixtures" / "panel_reconstruction.npz"
DOF = ("surge", "sway", "heave", "roll", "pitch", "yaw")


@pytest.fixture(scope="module")
def data() -> dict:
    if not FIXTURE.is_file():
        pytest.fail(
            f"{FIXTURE} is missing -- regenerate with artifacts/make_panel_fixture.py. "
            "Without it G1.6 has no CI evidence, which is the state AN2 closed."
        )
    d = np.load(FIXTURE, allow_pickle=True)
    return {k: d[k] for k in d.files}


def _reconstruct(d: dict, area: np.ndarray | None = None) -> np.ndarray:
    """Generalized force from the panel field. Capytaine's own DOF displacement
    fields are used rather than a reconstructed moment arm, so no rotation centre
    is assumed -- the assumption `conventions.md` forbids."""
    a = d["area"] if area is None else area
    w = np.einsum("pc,jpc->jp", d["normal"], d["dof_fields"]) * a
    return -np.einsum("jp,kp->jk", w, d["radiation"])


def _target(d: dict) -> np.ndarray:
    om = float(d["omega"][0])
    return om**2 * d["A"] + 1j * om * d["B"]


def _residual(R: np.ndarray, T: np.ndarray) -> float:
    return float(np.linalg.norm(R - T) / np.linalg.norm(T))


def test_the_fixture_is_non_trivial(data: dict) -> None:
    """Meta-test. Every assertion below is vacuous on an empty or degenerate
    fixture -- and an all-zero pressure field would satisfy the identity."""
    assert data["radiation"].shape[1] >= 32, "too few panels to be a real integration"
    assert int(data["n_bodies"][0]) >= 2, "a single body cannot show cross-coupling"
    assert np.abs(data["radiation"]).max() > 0.0, "pressure field is identically zero"
    assert np.linalg.norm(_target(data)) > 0.0, "reference is identically zero"


def test_panel_reconstruction_matches_the_bem_coefficients(data: dict) -> None:
    """G1.6, all rows."""
    r = _residual(_reconstruct(data), _target(data))
    assert r < PANEL_RECONSTRUCTION_RESIDUAL, (
        f"panel reconstruction residual {r:.3e} exceeds " f"{PANEL_RECONSTRUCTION_RESIDUAL:.0e}"
    )


@pytest.mark.parametrize("half, rows", [("translational", (0, 1, 2)), ("rotational", (3, 4, 5))])
def test_both_halves_reconstruct(data: dict, half: str, rows: tuple[int, ...]) -> None:
    """AK2: the rotational rows carry the largest historical excess and were the
    last to be covered. They are asserted separately so a regression confined to
    one half cannot hide inside a combined norm."""
    n = int(data["n_bodies"][0])
    idx = [6 * b + c for b in range(n) for c in rows]
    R, T = _reconstruct(data), _target(data)
    r = _residual(R[idx], T[idx])
    assert r < PANEL_RECONSTRUCTION_RESIDUAL, f"{half} rows: residual {r:.3e}"


def test_dead_dof_are_excluded_from_the_per_dof_reduction(data: dict) -> None:
    """AI4: a ratio of two round-off quantities reads as a pass and is not one."""
    n = int(data["n_bodies"][0])
    T = _target(data)
    ref = np.array([np.linalg.norm(T[[6 * b + c for b in range(n)]]) for c in range(6)])
    mask = live_dof(ref)
    assert mask.any(), "every DOF is dead -- nothing was reconstructed"
    kept = over_live(np.arange(6), ref, what="per-DOF rows")
    assert len(kept) == int(mask.sum())


def test_a_single_perturbed_panel_BREAKS_the_identity(data: dict) -> None:
    """Negative control, and the gate's own failure mode (eighth guard).

    Without this the assertions above pass on any fixture whose numbers happen to
    agree, and would keep passing if `_reconstruct` were silently changed to
    return the target. Perturbing ONE panel of 64 by 1% must leave the tolerance
    by orders -- it moves the 10,560-panel platform case to 1.082e-05.
    """
    bad = data["area"].copy()
    bad[0] *= 1.01
    r = _residual(_reconstruct(data, area=bad), _target(data))
    # Consumes the COUNTER value rather than a local multiple of the ceiling
    # (AO1): the counter-case must be a number an executable test uses, or it is
    # prose. Widening PANEL_RECONSTRUCTION_RESIDUAL toward the counter-case is
    # caught by test_the_ceiling_sits_below_its_counter_case; this asserts the
    # counter-case is a magnitude a REAL defect actually reaches.
    assert r >= PANEL_RECONSTRUCTION_RESIDUAL_COUNTER, (
        f"perturbing one panel moved the residual only to {r:.3e}, below the "
        f"declared counter-case {PANEL_RECONSTRUCTION_RESIDUAL_COUNTER:.3e}. "
        "Either the identity is not sensitive to the geometry it integrates over, "
        "or the counter-case was chosen rather than measured."
    )


def test_the_reference_has_the_shape_of_a_bem_result(data: dict) -> None:
    """Structural checks only -- and the limitation is the point.

    The circularity worth guarding is one of PROVENANCE: if `A`/`B` had been
    derived from the panel field rather than read from the solver, the identity
    would hold by construction and this gate would measure nothing (the failure
    AK1 records for quadrature under AF3).

    **That cannot be asserted numerically.** A first version of this test tried,
    by requiring `Re(R)/w^2` to differ from `A` -- which is asserting the identity
    is FALSE, since `Re(T) = w^2 A` is exactly what the identity says. Provenance
    is invisible in a pass/fail (tenth guard), and it is guaranteed by
    `artifacts/make_panel_fixture.py` reading `result.added_mass`, not by anything
    here.

    What is checkable is that the two sides have the right *kind*: a complex
    pressure field, and real coefficient matrices the solver produces.
    """
    assert np.iscomplexobj(data["radiation"]), "pressure field must be complex"
    assert np.isrealobj(data["A"]) and np.isrealobj(data["B"]), (
        "A and B must be real -- complex ones would suggest they were derived "
        "from the pressure field rather than read from the solver"
    )
    n = int(data["n_bodies"][0])
    assert data["A"].shape == data["B"].shape == (6 * n, 6 * n)
    assert data["dof_fields"].shape == (6 * n, data["radiation"].shape[1], 3)
