"""FloatSim's time integrator, as the FE side has to know it (R653).

WHY THIS MODULE EXISTS. The replay driver reconstructs the generalized-alpha step
FloatSim took, so that `res.lam` can be read back as joint reactions. Every coefficient
of that step follows from one number, the spectral radius at infinity `rho_inf`, and that
number lived as a bare constant in `scripts/report_joint_reactions.py` where nothing
asserted it:

    cmd: grep -rn RHO_INF tests/ floatfea/
    out: (no output) -- nothing asserted this value

R653 carried that gap from F3, on the condition that it becomes blocking "if a G4.x gate
ever cites this residual as evidence that FloatSim's scheme is reproduced". F4 step 2's
G4.1 does exactly that: it reports a per-body equilibrium residual computed from the
reconstructed step. So the parameter moves here, where the FE side declares it, and the
derivation that follows from it is written once.

WHAT THIS IS NOT. It is not a tolerance -- no comparison is made against it -- so it does
not belong in `floatfea/tolerances.py`. It is not apparatus either: it is one closed-form
formula and the constant it is evaluated at, both of which the step's own gate needs.
"""

from __future__ import annotations

from pathlib import Path
from typing import Final, NamedTuple

import yaml

FLOATSIM_RHO_INF: Final[float] = 0.8
"""The spectral radius at infinity the replay driver reconstructs with.

**THIS STUDY'S VALUE (`platform_rao_pilot.py:291`); FloatSim's DEFAULT is 0.9**
(`floatsim/solver/newmark.py:222`). The distinction matters and an earlier version of this
docstring lost it by saying "FloatSim's value": a reader who took the default would
reconstruct the wrong step and the residual would move by two to three decades.

**IT IS THE DECLARED EXPECTATION, AND `rho_inf_from_deck()` IS THE ARTIFACT (R686).** This
constant is typed here from HSP's source line; the deck export carries the same number,
written by `scripts/export_platform_deck.py` out of HSP at the pinned tag. The gate
compares the two, so editing EITHER reddens -- which is the shape EB6 uses for the buoy
geometry and for the same reason. Before R686 the gate compared this constant with a
driver that had been assigned FROM it, so the claim was true by assignment and the deck
sat in the tree unread: setting the deck key to 0.9 -- the exact `0.05`-class disagreement
C131's "429x louder" was about -- left the suite green.

C131's finding is that a rule written twice drifts, and an earlier version of the driver
held two copies of this number. Varying the value moves the residual by about `1.0005x`,
so the constant is not what the residual is sensitive to -- a wrong RECONSTRUCTION is, by
two to three decades, and that sensitivity is the point of reconstructing at all.
"""

_DECK_YAML: Final[Path] = (
    Path(__file__).resolve().parents[2] / "data" / "platform" / "platform12_deck.yaml"
)


def rho_inf_from_deck(path: Path | None = None) -> float:
    """`simulation.spectral_radius_inf` from the pinned deck export (R686).

    The deck is generated by `scripts/export_platform_deck.py` from HSP's own builder at
    the pinned tag and its header says DO NOT HAND-EDIT, so this is the integrator
    parameter as HSP recorded it rather than as anyone typed it. It is the only occurrence
    of that key in the repository.

    The driver reconstructs with THIS, not with `FLOATSIM_RHO_INF`, so the number the
    replay uses comes from the export; the constant is the independent expectation the
    gate checks it against.
    """
    deck = yaml.safe_load((path or _DECK_YAML).read_text(encoding="utf-8"))
    simulation = deck["simulation"]
    if "spectral_radius_inf" not in simulation:
        raise KeyError(
            "the deck's `simulation` block carries no `spectral_radius_inf`. The replay "
            "cannot reconstruct FloatSim's step without it, and guessing is the one "
            "thing that must not happen here -- re-run scripts/export_platform_deck.py."
        )
    return float(simulation["spectral_radius_inf"])


class GeneralizedAlpha(NamedTuple):
    """The four coefficients of one generalized-alpha step."""

    alpha_m: float
    alpha_f: float
    beta: float
    gamma: float


def generalized_alpha_coefficients(rho_inf: float) -> GeneralizedAlpha:
    """`(alpha_m, alpha_f, beta, gamma)` from the spectral radius at infinity.

    Chung & Hulbert (1993), "A time integration algorithm for structural dynamics with
    improved numerical dissipation: the generalized-alpha method", eqs. (25)-(27):

        alpha_m = (2 rho_inf - 1) / (rho_inf + 1)
        alpha_f = rho_inf / (rho_inf + 1)
        beta    = (1 - alpha_m + alpha_f)^2 / 4
        gamma   = 1/2 - alpha_m + alpha_f

    `rho_inf` in `[0, 1]`: 1 is no dissipation, 0 is asymptotic annihilation. The
    enumeration is not checked here because this is a formula, not a validator -- the
    interchange reader is what refuses a record whose `integrator` block is wrong, and
    `docs/load-interchange-v1.md` sec.2 is where the field is specified.
    """
    alpha_m = (2.0 * rho_inf - 1.0) / (rho_inf + 1.0)
    alpha_f = rho_inf / (rho_inf + 1.0)
    return GeneralizedAlpha(
        alpha_m=alpha_m,
        alpha_f=alpha_f,
        beta=0.25 * (1.0 - alpha_m + alpha_f) ** 2,
        gamma=0.5 - alpha_m + alpha_f,
    )
